- orangecontrib/text/country_codes.py
- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/resources/geomap-script.js
Blocked on https://github.com/biolab/orange3/pull/474
> OWGeoMap: better handling of messy country (+US city) data

- README.md
- setup.py
Including long description into the package info and bumping a version.
> setup.py: Long description and version bump

- orangecontrib/text/widgets/owcorpusviewer.py
CorpusViewer was missing the option to display class variables.
> corpusviewer: added class vars for display

- orangecontrib/text/lda.py
- orangecontrib/text/tests/test_lda.py
- setup.py
Gensim unified the topics format as returned by 'show_topics' method in version 0.12.3. Consequently some code changes were required.
> lda: fixed code according to new format of 'show_topics'

- orangecontrib/text/corpus.py
- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owloadcorpus.py
- orangecontrib/text/widgets/ownyt.py
Corpus.documents before contained the list of strings. Now this is generated on the fly.
> Generate corpus.documents on the fly

- orangecontrib/text/preprocess.py
- orangecontrib/text/tests/test_stemmatizer.py
- orangecontrib/text/widgets/owbagofwords.py
- orangecontrib/text/widgets/owpreprocess.py
This bugs clauses exceptions in Preprocessor and Bag of Words widgets.
> Minor preprocessor bug fixes

- orangecontrib/text/nyt.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owwordcloud.py
Won't work until https://github.com/biolab/orange3/pull/1034 is merged.
> OWWordCloud: Add Save graph button

- .gitignore
- orangecontrib/text/datasets/README.txt
- scripts/parse-friends-transripts.py
Also added a small fix for load corpus: only string attributes can be used as text features.
> friends: Added a data set with Friends transcripts

- orangecontrib/text/widgets/owgeomap.py
Fixes https://github.com/biolab/orange3-text/issues/4
> OWGeoMap: load local resources from correct URL on Windows

- orangecontrib/text/bagofowords.py
- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_bag_of_words.py
- orangecontrib/text/widgets/owbagofwords.py
Updated the Bag Of Words widget, so it can be used with the current text mining workflow.
> BagOfWords

- orangecontrib/text/widgets/owwordcloud.py
Blocked on https://github.com/biolab/orange3/issues/1217
> OWWordCloud: adapt to work without gui.TableWidget that was recently purged

- orangecontrib/text/bagofowords.py
- orangecontrib/text/corpus.py
- orangecontrib/text/lda.py
- orangecontrib/text/preprocess.py
- orangecontrib/text/widgets/owbagofwords.py
- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/owlda.py
- orangecontrib/text/widgets/owloadcorpus.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/owwordcloud.py
Modifications in accordance with new preprocessing:
* Added `tokens` property to `Corpus`. If some preprocessing was done beforehand use it else run default Preprocessor.
* Adopted LDA & WordCloud to use `Corpus.tokens`
* BoW now makes a copy of Corpus.
> Use new Preprocessing

- .travis.yml
- doc/widgets/preprocess.rst
- requirements.txt
- travis/install_orange.sh
Since Orange3 came on pip it can be added among our requirements.
> Adding Orange as dependency

- orangecontrib/text/preprocess.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
… order. Added a new option to generate tokens without punctionation.
> PREPROCESS: Twitter, NLTK (no punctuation) tokenizers

- orangecontrib/text/bagofowords.py
- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Blocked on [orange3#1306](https://github.com/biolab/orange3/pull/1306).
> BoW Sparse

- orangecontrib/text/corpus.py
- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
Makes tokens and dictionary immutable
> Preprocess copy

- orangecontrib/text/widgets/owpreprocess.py
> Fix Enter Issues

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
Add Regex as a token filtering option.
> RegExp Token Filter

- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/utils/widgets.py
Added an explanation to Query Text Edit on how lines are joined.
> Add Placeholder to Twitter's Query

- orangecontrib/text/widgets/owwordcloud.py
Rename Topics to Topic.
Fix crash while changing slider value if no data is present.
> OWWordCloud fixup

- orangecontrib/text/widgets/owwordcloud.py
Btw, `debug=True` can be used to debug JS issues, like slowness on Mac. Possibly.
> OWWordCloud: instantiate WebView differently (fwd-compat)

- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owtwitter.py
Print nicer error message when rate limit is exceeded.
> Twitter: Nicer error on rate limit

- orangecontrib/text/widgets/owcorpusviewer.py
Corpus('friends-transcripts') -> CorpusViewer speed up from ~1m to ~10s.
> CorpusViewer: Speed-up sending umnatched

- orangecontrib/text/corpus.py
- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/tests/test_utils.py
- orangecontrib/text/tests/test_wikipedia.py
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/owwikipedia.py
- orangecontrib/text/widgets/utils/widgets.py
- orangecontrib/text/wikipedia.py
Wikipedia & Twitter refactored to always download all features. Only selected StringVariables go into text_features. Also all features for Twitter were moved to meta attributes.
> Wikipedia & Twitter Download All Features

- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/resources/geomap-script.js
And some other simplifications.
> OWGeoMap: layout WebviewWidget manually (fwd-compat)

- orangecontrib/text/stats.py
- orangecontrib/text/tests/test_stats.py
- orangecontrib/text/widgets/owwordenrichment.py
Also introduce new style warnings.
> OWWordEnrichment fix for Sparse

- orangecontrib/text/widgets/owduplicates.py
> OWDuplicates

- README.md
A tentative update of readme.md for installation of Orange3-Text. Some testing needs to be done.
> Updated README.md for Text

- orangecontrib/text/corpus.py
- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/preprocess/tokenize.py
- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/vectorization/simhash.py
This PR enables storing a classifier trained on BoW data and then loading and applying it on new data. The new data should not be preprocessed or vectorized since feature's compute values will preprocess and vectorize the new data in the same way as it was done when learning a classifier.
One problem still persist:
* When the data contains some features in X, the BoW model on new data will be dense. This is the consequence of `Table.from_table` retaining the initial sparsity structure of arrays.
> BoW Support Storing & Loading a Classifier

- orangecontrib/text/topics/topics.py
- orangecontrib/text/vectorization/bagofwords.py
This fixes crashes of Topic Modelling widget on POS data.
> [FIX] Topics Modelling on POS data

- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/utils/widgets.py
Refactor of OWTwitter. New features:
* Use user_timeline to obtain tweets older than two weeks.
* Refactoring to OWConcurrentWidget.
* Reorder GUI a bit.
> OWTwitter Search by Author using Timelines

- orangecontrib/text/widgets/owduplicates.py
Duplicate detection only works when distances are calculated between rows; and cannot work on distances between columns. When we get distances between columns on input raise an error and do nothing.
> OWDuplicates: Raise error on distances between columns

- orangecontrib/text/widgets/owwordenrichment.py
Add additional checks to show errors when selected data is empty or all examples are selected.
> [ENH] OWWordEnrichment: Refactor Error Messages

- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/resources/geomap-script.js
- orangecontrib/text/widgets/resources/owgeomap.html
WebEngine in PyQt 5.7.0 does not allow to open local contetn from html files due to a bug (https://bugreports.qt.io/browse/QTBUG-55902).
Needs testing on PyQt4.
> OWGeoMap PyQt5 fixup

- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_nyt.py
- orangecontrib/text/widgets/ownyt.py
A few fixes regarding OWNYT:
* Catch URLErrors; fixes #182.
* Catch BadStatusLine errors; fixes #184.
* Show an error message when there is no internet connection.
> [FIX] OWNYT: Improve Behaviour when No Internet Connection

- requirements.txt
> Requirements: Bump Orange version to 3.3.10

- orangecontrib/text/tests/test_vectorization_base.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/widgets/owwordenrichment.py
Fixes #220.
WordEnrichment takes only BoW features.
> WordEnrichment Use Only BoW Features

- orangecontrib/text/widgets/owduplicates.py
Fixes https://github.com/biolab/orange3-text/issues/216
Save threshold as a setting.
> OWDuplicates: save threshold as setting

- orangecontrib/text/widgets/utils/widgets.py
Fixes #205. 
Check if path empty.
> FileWidget: check if path None

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/resources/wordcloud-script.js
- orangecontrib/text/widgets/resources/wordcloud2.js
Fixes https://github.com/biolab/orange3-text/issues/215.
[wordcloud2](https://github.com/timdream/wordcloud2.js) is updated. Selection is saved in workflow. Colors  and word tilts are adapted.
> Word Cloud: style refactoring & save selection

- orangecontrib/text/widgets/owloadcorpus.py
> [FIX] Corpus: settings

- orangecontrib/text/widgets/owwordcloud.py
Fixes https://github.com/biolab/orange3-text/issues/246
> OWWordCloud: clear wordcloud upon empty signal

- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/widgets/tests/test_owbagofwords.py
https://sentry.io/biolab/orange3-text-bl/issues/256663954/
Don't run BoW vectorizer when no instances.
> [FIX] Bag of Words: test and prevention empty data

- orangecontrib/text/nyt.py
Number of words represented by DiscreteVariable and not ContinuousVariable.
> [FIX] NY Times: Change word count to a continuous variable

- orangecontrib/text/widgets/owcorpusviewer.py
> [FIX] Corpus Viewer: settings

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Add extend method, which enables concatenating and extending Corpora
> [ENH] Corpus: extend

- orangecontrib/text/widgets/owwordcloud.py
Weights couldn't be exported from Word Cloud.
New Weights signal added. Can be exported as a Table.
> Add weights output to Word Cloud

- orangecontrib/text/widgets/resources/wordcloud-script.js
Fixes https://github.com/biolab/orange3-text/issues/273
> OWWordCloud: fix showing of min-weighted words

- orangecontrib/text/widgets/utils/widgets.py
Fixes #271
Store `(none)` in settings.
> [FIX] FileWidget: Store (none) in Settings

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/owloadcorpus.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owtweetprofiler.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/owwikipedia.py
- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owworldclooud.py
- orangecontrib/text/widgets/utils/owbasevectorizer.py
- requirements.txt
> Widget: new signals

- orangecontrib/text/tests/test_tweetprofiler.py
- orangecontrib/text/tweet_profiler.py
- orangecontrib/text/widgets/owtweetprofiler.py
Various improvements of Tweet Profiler.
* Remove tokens verifications.
* Remove info box.
* Mark probabilities features as not hidden.
* Don't rerun with the same parameters.
> Tweet Profiler Cleanup

- orangecontrib/text/__init__.py
- orangecontrib/text/preprocess/__init__.py
- orangecontrib/text/sentiment/__init__.py
- orangecontrib/text/tag/pos.py
Refactor NLTK data downloading.
* Move sentiment dependencies to its module.
* Remove unnecessary `downoad_dir` arguments so NLTK data directory is set in one place.
> NLTK Data Download Refactor

- orangecontrib/text/topics/topics.py
- orangecontrib/text/widgets/owtopicmodeling.py
Fixes #278.
Add additional output of words representation in topic space.
> [ENH] Topic Modelling: Output a Table of Word Representation in Topic Space

- orangecontrib/text/widgets/owwordcloud.py
This has been making me cringe for way too long.
Make  no tilt a default in WC.
> Set default to no tilt in Word Cloud

- orangecontrib/text/widgets/owbagofwords.py
- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/owpubmed.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/owsimhash.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owtweetprofiler.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/owwikipedia.py
- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/owwordenrichment.py
Priority counts got out of hand + new widgets were introduced.
Priority counts updated. Tentative order:
100-199: data widgets
200-299: preprocessing
300-399: embeddings
400-499: topic modelling
500-599: visualizations
600-: other
> [RFC] Reorder widgets, unify priority

- doc/index.rst
- doc/scripting/bagofwords.rst
- orangecontrib/text/vectorization/bagofwords.py
Implements #231 
Added basic documentation for Bag of Words.
> Scripting documentation for BoW

- orangecontrib/text/widgets/owconcordance.py
No report.
Send report added.
Bug in `rowCount` fixed.
> Concordances: add Send Report

- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Fixes https://github.com/biolab/orange3-text/issues/327
Don't modify class instances in-place.
> OWPreprocess: allow more than one instance on canvas

- orangecontrib/text/widgets/owpreprocess.py
> Enhance regex filtering

- orangecontrib/text/vectorization/bagofwords.py
Fixes #348 
Fix error for documents with no tokens.
> [FIX][RFC] bagofwords: fix error on document with no tokens

- orangecontrib/text/guardian.py
Might perhaps fix #354. 
Add a credentials parameter for the widget to run.
> Attempt at fixing failing Guardian tests

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_concordances.py
Fixes #352.
Clear selection when query word changes.
> Concordance: clear selection on changing word

- requirements-doc.txt
Introduced separate requirements file for ReadTheDocs.
New file copied from core Orange.
> Separate requirements file for Readthedocs

- readthedocs.yml
- rtd_environment.yml
> Attempt at resolving failing docs

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
Fixes #374
Multiple classes are set in the same class attribute
> [FIX] OWCorpusViewer: fix search highlighting

- requirements.txt
- setup.py
Ufal.udpipe broken on OSX.
New release that fixes broken dependency for OSX - ufal.udpipe.
> Release 0.5.1

- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Fixes #393 
If no internet connection, use previously stored local models. If no such models exist, disable UDPipe.
> [FIX] OWPreprocess: upgrade UDPipe to work offline

- orangecontrib/text/tests/__init__.py
- requirements.txt
- setup.py
Travis tests does not pass
Test suite moved to `__init__.py` in orangecontrib.text.tests.
> Updated test suit for Travis to pass

- orangecontrib/text/guardian.py
> TheGuardian: fixed displaying of Unicode characters

- orangecontrib/text/widgets/owpreprocess.py
Continuation of #409. 
Changing values in n-grams commits automatically.
> Preprocess Text: changing n-grams commits automatically

- .travis.yml
- .travis/install_orange.sh
Travis did not test on latest Orange master.
Add scripts to test on master.
> Travis: run tests on master

- conda_environment.yml
Documentation travis test fails due to problematic biopython version.
biopython version restriction removed from conda_environment.yml
> Fix documentation build test

- orangecontrib/text/widgets/ownyt.py
In https://github.com/biolab/orange3-text/pull/445 I produced a wrong import.
It is fixed with this PR.
> Fix: broken import

- .travis.yml
Numpy and openTSNE incompatible with latest versions.
Fix failing tests with numpy dependency issues.
> Fix failing tests

- orangecontrib/text/widgets/owdocmap.py
Since GeoMap was renamed, it also needs a mapper for backward compatibility.
Add "replaces" option.
> Add replaces to DocMap

- doc/widgets.json
- orangecontrib/text/widgets/owbagofwords.py
- orangecontrib/text/widgets/owdocmap.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/owsimhash.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owtweetprofiler.py
Widgets lack keywords.
Add keywords.
> [DOC] Add keywords to widgets and update widget.json file

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_owconcordances.py
Fixes #449. 
Add Concordance output as text feature, not document.
> Set concordance as text feature

- doc/widgets/bagofwords-widget.md
- doc/widgets/corpus-widget.md
- doc/widgets/preprocesstext.md
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
- orangecontrib/text/widgets/utils/tests/test_owbasevectorizer.py
Topic Modelling and test_owbasevectorizer failed in certain settings.
Update Topic Modeling to new Orange.
Have BaseVectorizer tests pass on 3.21, too.
> Small fixes

- MANIFEST.in
Some of the files were missing from source distribution. 
Update MANIFEST so that it includes missing files.
> manifest: update source dist files

- .travis.yml
Orange has some bugs since scikit-learn got updated and tests fail. It will not be fixed until the new Orange is released. 
Temporary fix: manually set version of scikit-learn for Travis.
> Temporary tests fix

- orangecontrib/text/widgets/owwordenrichment.py
Fixes #516.
Changed column to sort by.
> Word Enrichment: sort by p-value

- .travis.yml
Tests started to fail after the new release of pyqt
Added packages that are needed with the new version of pyqt
> Debug xfb issue

- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/tests/test_owtwitter.py
Fixes #535. 
Twitter outputs Author as a meta variable.
> Don't set Twitter author as class variable

- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
Corpus is blocking main thread when loading bit larger file
Run file loading in a separate thread
> Corpus: Run file loading in a separate thread

- orangecontrib/text/widgets/owcorpustonetwork.py
Fixes https://github.com/biolab/orange3-text/issues/555
- Fixing issue with the widget not showing up
- Code refactoring with black
> [FIX] Corpus to network

- .travis.yml
- .travis/install_orange.sh
Fixes #518 
It makes only one test case uses orange3-network
> Travis: a test case with orange3-network

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/tests/test_owwordcloud.py
Fixes https://github.com/biolab/orange3-text/issues/580
- Fixes https://github.com/biolab/orange3-text/issues/580
- test_owworldcloud -> test_owwordcloud
> [FIX] owwordcloud: Work with empty token list

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_corpus.py
Fixes (partially) #590 - pickling error
Transformed _lexicons which were dict_keys before to lists, to allow pickling
> Fix corpus pickling error

- CHANGELOG.md
- scripts/create_changelog.sh
- Changelog is out of date
- Changelog script is not working
Updated changelog and script
> Fix changelog

- orangecontrib/text/widgets/owcorpustonetwork.py
Fixes https://github.com/biolab/orange3-text/issues/600
Register output type by its qualified name.
> owcorpustonetwork: Register type by qualified name

- .github/FUNDING.yml
No Sponsor button available.
Adds Sponsors button.
> Add Github Sponsors link

- orangecontrib/text/sentiment/__init__.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
Sentiment Analysis was written suboptimally. Refactoring much needed.
- Move common code to base class Sentiment.
- Simplify classes.
- Move common code to base class SentimentDictionary, which handles data loading.
- Preprocessing applies also LowercaseTransform (necessary for dictionaries!).
- Preprocessing is done at set_corpus to avoid preprocessing at every change of a method.
- supported_languages is not only a method
- Give names to methods.
> Sentiment Analysis: Refactor

- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/tests/test_owtwitter.py
Widget status is not set as in progress correctly when downloading tweets.
Download tweets in threads with the concurrent mixin.
> Twitter use ConcurrentWidgetMixin and update test

- orangecontrib/text/import_documents.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/tests/test_owimportdocuments.py
> [FIX] Import Documents: Handle loading folder with no readable files

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
> [FIX] Corpus Viewer: Handle empty corpus

- orangecontrib/text/widgets/owwordlist.py
- orangecontrib/text/widgets/tests/test_owwordlist.py
- requirements.txt
> [ENH] Word List: New widget

- orangecontrib/text/keywords/__init__.py
- orangecontrib/text/keywords/rake.py
This PR implements methods for keyword extraction.
> Keywords methods

- orangecontrib/text/widgets/tests/test_owkeywords.py
After latest YAKE! release some OWKeyword tests fail.
Fix tests.
> Keywords: Fix test due to latest YAKE! release

- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Fixes #670.
Add a box with counts of tokens and types.
> OWPreprocess: Add information on tokens

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
Implements #659.
Add information on a number of query matches.
Clean up Info box.
> Corpus Viewer: Display the number of query matches

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owwordcloud.py
Some widgets with multiple outputs didn't have the default output set.
Set default outputs for all.
> Set default outputs

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/owdocmap.py
- orangecontrib/text/widgets/owstatistics.py
Fixes #624. 
Small changes to window sizes for nicer views.
Affected widgets: OWConcordance, OWStatistics, OWDocMap
> UI fixes: DocMap, Concordance, Statistics

- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owwordenrichment.py
Implements #705. 
Add an output to Word Enrichment containing the displayed results.
> OWWordEnrichment: Output results

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/__init__.py
- orangecontrib/text/widgets/tests/__init__.py
Attempt to fix failing tests.
- disable lock in tests
- handle 1D and 2D Y arrays in corpus
> Handle failing tests

- .github/workflows/rebase.yml
> Add automatic rebase on /rebase

- orangecontrib/text/widgets/owstatistics.py
Fixes #733. 
Make buttons the same as in Merge Data.
Put Apply button to buttonsArea.
> OWStatistics: update GUI

- orangecontrib/text/widgets/owscoredocuments.py
Distribution bars are all full-length for values greater than 1.
Fix distribution bars to show the real ratio of the column.
> [FIX] Score documents: fix distribution bars for values > 1

- doc/widgets/documentembedding.md
Server communication not explained in detail.
Explain how embedding works server-side.
> [DOC] Document Embedding: Explain how server communication works

- orangecontrib/text/twitter.py
Twitter widget does not work on Python 3.10
Fix a legacy import.
> [FIX] Twitter: Update for Python 3.10

- orangecontrib/text/widgets/utils/owbasevectorizer.py
- orangecontrib/text/widgets/utils/tests/test_owbasevectorizer.py
Fixes #764.
Reset properties on None.
> Base Vectorizer: reset data when None on input

- orangecontrib/text/widgets/owcorpusviewer.py
> Corpus Viewer: full image path

- orangecontrib/text/widgets/owtwitter.py
> Twitter: accept @author as author

- orangecontrib/text/keywords/__init__.py
- orangecontrib/text/tests/test_keywords.py
Simplify keywords.AggregationMethods code (remove duplicate code).
> AggregationMethods: Refactor

- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
> OWPreprocess: added tests for absolute frequency filter

- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/__init__.py
- orangecontrib/text/topics/nmf.py
- orangecontrib/text/widgets/owtopicmodeling.py
Fixes #684.
Continues #844.
We decided to wait with DTM for now, because gensim's implementation is too slow.
Add NMF from gensim.
Add docs later!
> Topic Modelling: Add NMF method

- orangecontrib/text/import_documents.py
- orangecontrib/text/pubmed.py
- orangecontrib/text/tests/test_pubmed.py
- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/owcorpustonetwork.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owtweetprofiler.py
- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
- orangecontrib/text/widgets/tests/test_owstatistics.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owwordenrichment.py
Across the addon there are multiple warnings (mostly connected to deprecations) including warnings regarding deffered commits.
Changes from this PR resolve warnings.
> Resolve warnings

- orangecontrib/text/__init__.py
- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/widgets/owcollocations.py
- orangecontrib/text/widgets/tests/test_owcollocations.py
- requirements.txt
- tox.ini
Since the release of Orange3==3.33, two tests have started to fail.
Remove failing tests according to descriptions.
> Remove deprecations

- orangecontrib/text/tests/test_documentembedder.py
> Document embeddings tests - remove use of deprecated cancelled

- .github/workflows/rebase.yml
Automatic rebase is currently implemented at each repo seperately
Use reusable workflow instead
> Actions - automatic rebase - reusable workflows

- orangecontrib/text/widgets/owcreatecorpus.py
- orangecontrib/text/widgets/tests/test_owcreatecorpus.py
Added language field to he widget and language information to the corpus.
> [ENH] Create Corpus - add language to corpus

- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_nyt.py
- orangecontrib/text/widgets/ownyt.py
Some NYT tests are blocking for over 2 s
Speedup tests and small refactoring in tests and widget
> NYT - speedup tests and small refactoring

- orangecontrib/text/widgets/tests/test_owontology.py
Ontology tests request the server and are, therefore, slow and prone to the connection issues. 
Patch requests to the server to speedup
> Ontology - speed up tests

- orangecontrib/text/widgets/tests/test_owpreprocess.py
Some test cases request the server (UDPipe normalizer). 
Mock all requests to the server to speedup the tests
> Preprocess - speedup tests

- orangecontrib/text/widgets/tests/test_owannotator.py
Since annotator call t-SNE and some other heavy algorithms in the background tests are a bit slow
Using smaller dataset where possible to speedup tests
> Annotator - speedup tests

- orangecontrib/text/corpus.py
To be consistent with orange3 (https://github.com/biolab/orange3/pull/6366).
- rename summarize function
> Corpus: Use different names for single-dispatched functions

- orangecontrib/text/sentiment/__init__.py
Trouble with translating to Slovene.
Modified code so we could translate the names of Vader sentiments to Slovene.
> Vader sentiment: modified for better translation

- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/owtweetprofiler.py
Nothing much.
Some `()`, `[]` and ` ` modified for code beautifications.
> Duplicates, Guardian, Tweet profiler: code beautifications

- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/widgets/owbagofwords.py
Trouble with translating to Slovene. 
Modified code so we could translate widget to Slovene.
> BOW: modified code for better translation

- orangecontrib/text/widgets/owldavis.py
- orangecontrib/text/widgets/tests/test_owldavis.py
Report crashes on no data (Issue #971 ).
If there is no data, blank report shows up.
And also test for report is changed according to the changes in widget file.
> LDAvis: fixes with report error

- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
Slight problem for translation - can't get "Mean", "Sum",... to be translated.
- Added list of aggregator items - slightly modified code according to this change,
- moved report to widget file and
- added test for send_report and fixed test for `document_embedder`.
> Document embedder: modification for translation

- orangecontrib/text/widgets/resources/wordcloud2.js
Fixes https://github.com/biolab/orange3-text/issues/987
Since the newer version of the wordcloud2.js library is available, I am updating the library from https://github.com/timdream/wordcloud2.js
> [FIX] Word Cloud - Update wordcloud javascript library

- doc/widgets/twitter-widget.md
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/tests/test_owtwitter.py
Closes https://github.com/biolab/orange3-text/issues/995
Twitter changed their API plans, so users can no longer download Tweets with the Free plan. Add note to the notification
> [FIX] Twitter - Add note about plan requirements/changes to the documentation

- orangecontrib/text/tests/test_corpus.py
Summaries slightly changed in Orange
Adopt tests to changes
> Summary - Adopt tests to changes in Orange

- tox.ini
> Tox updates

- orangecontrib/text/widgets/owcollocations.py
For some reason, header names were off in Collocations.
Set correct column names.
> OWCollocations: fix header names

- .github/workflows/release.yml
> [CI] Update release.yml - Fix branch

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
Fixes #1028.
Read UTF-8 files with proper encoding.
> Sanitize stopwords with BOM

- setup.py
> Bump version: 1.16.0

- orangecontrib/text/import_documents.py
> [FIX] import_documents: rewrite proxies to mounts for httpx 0.28

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
In `set_text_features` the attributes of attributes did not get written to the output table.
Ensure all changes in `text_features` property are reflected in the attributes of attributes tags.
> Corpus: Ensure proper adding and removing of attributes of attributes
