biolab/orange3-text

- orangecontrib/text/widgets/owgeomap.py
The bug was e.g. 'slovenia ' not matching. `str.strip`ping resolved.
> OWGeoMap: fix bug with not enough instances passed through

- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_preprocess.py
Corpuses are not loaded any more from txt files but as tab files.
Updated the tests and commented out the preprocessing test for which
the code is not yet implemented.
> tests_corpus, tests_preprocess: Updated tests to tab

- .travis.yml
- travis/nltk_download.sh
Downloading all NLTK data was slowing the build process significantly. Since we only need WordNet, downloading other stuff is unnecessary and was removed.
Also, we now delete pip log messages to prevent them from triggering a new cache packaging and archiving.
> Speeding-up Travis-CI build

- setup.py
Revert once smart_open>=1.3.1 releases.
Fixes https://github.com/biolab/orange3-text/issues/15
> setup.py: freeze smart_open dependency to git version

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Added support for `Corpus.from_file('bookexcerpts')` which looks in default corpora location. Also added equality for corpus.
> corpus: from_file looks in default corpora location

- requirements.txt
- setup.py
The missing `scipy` requirement somehow only now broke the travis build.
> Fixing broken tests

- orangecontrib/text/nyt.py
For now, I suggest setting the missing values back to empty string, since it is more compliant with other widgets.
> NYT missing values

- travis/install_orange.sh
Fixing orange installation. Due to changes in Orange, we need to update the `install_orange.sh` script.
> fixing Orange installation script

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Checking if the domain is present did not work for some data sets. `if domain` only checks for features and class vales, but not metas. Consequently, inferring was skipped for datasets with only meta attributes.
> [WiP] corpus: fix condition for inferring text features

- orangecontrib/text/bagofowords.py
- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owloadcorpus.py
* CorpusViewer adopted for Tables. Instead of searching in `corpus.documents` it searches in `Search features` and it displays `Display features`.
* CorpusViewer skip Bag-of-Words features.
* LoadCorpus allows attributes and class_vars for mining.
> CorpusViewer: Support Table, search in Search features

- orangecontrib/text/corpus.py
`attributes` attribute was added to Orang Table. Currently not having it might cause some problems when saving data.
> [FIX] Corpus: Add attributes

- orangecontrib/text/corpus.py
When we create a copy of corpus _tokens and _dictionary should be copied as well.
> Corpus: Fix copy to copy _tokens and _dictionary

- orangecontrib/text/widgets/owloadcorpus.py
Allow all formats that are supported in Orange.
> OWLoadCorpus: Allow all Orange formats

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_preprocess.py
Currently when indexing a corpus preprocessing is lost. This PR introduces two changes:
- Before storing tokens cast them to `ndarray`. This makes indexing easier and unifies the type of `tokens` with `X`, `Y` and `metas`.
- Implement `Corpus.__getitem__` that retains preprocessing.
> Implement __getitem__ for Corpus

- orangecontrib/text/widgets/owloadcorpus.py
When reloading schemas the most recent file was selected but was not loaded. Calling `widget.select` resolves the issue.
> OWLoadCorpus: Load first file in __init__

- orangecontrib/text/widgets/owpreprocess.py
Fixes #81. Emitting `change_signal` in `on_toggle` is redundant since it also calls `display_widget`. Inside `display_widget` we set `self.value` and since value setters itself emmits `change_signal` we shouldn't re-emit it inside `on_toggle`.
> OWPreprocessor: Remove redundant change_signal.emit()

- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/utils/widgets.py
@nikicc has mentioned (#72) that OWTwitter can produce 403 error. This PR is supposed to fix it.
> Twitter: allow empty word list

- orangecontrib/text/vectorization/simhash.py
int type causes crash while connecting OWSimhash with OWHeadMap.
> Simhash: fix crash in HeatMap

- orangecontrib/text/corpus.py
Table's `ensure_copy` can only work for numpy arrays and not sparse data. Hence to support this also for sparse we should make copies. Fixes #85.
> Corpus: Fix copy for sparse data

- orangecontrib/text/credentials.py
- orangecontrib/text/tests/test_credentials.py
- orangecontrib/text/widgets/owtwitter.py
- requirements.txt
This PR proposes two changes to APICredentialDialogs. I.e. to use:
- credential manager to store passwords in system keyring services,
- `OWWidget` instead of `QDialog` directly.
**Credential Manager:**
Storing API keys in settings is problematic due to many reasons. The most annoying one for developers being the need to re-input all keys one settings are reseted. Moreover, settings are allegedly saved in plain text and also inside schemas, which is problematic when sending schemas around to others.
Here proposed Credential Manager stores API keys in system keyring services like Keychain, Credential Vault, Secret Service, etc. One consequence of this is that we now store only one key instead of many as we did before. The example of usage is shown on the Twitter Widget.
**OWWidget:** …
> Twitter: Use Credential Manager for API Keys

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/widgets/owpreprocess.py
- Token frequency set to 100
- Stopword list capitalized
- N-grams and POS tagger turned off by default
- when n-grams are on, default is (1,2)
> [RFC] Changed defaults for Preprocess

- .travis.yml
Missing `version.py` seems to break travis tests due to failing imports of `orangecontrib.text`.
> Fix Version Imports for Travis

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
Two bug-fixes for CorpusViewer:
- Corpus.from_corpus did not retain preprocessing. It was removed since the same can much simpler be achieved by indexing.
- When display features were reordered marking didn't highlight the correct features.
> CorpusViewer: Retain Preprocessing & Fix Marking for Reordering

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
`FrequencyFilter` seems to be quite slow so its wasteful to run it every time in preprocessing. Currently we run it (with min_df=0, max_df=1 so no tokens are filtered out) even it the user did not provide any `FrequencyFilter`. 
```py
>>> p = Preprocessor(tokenizer=WordPunctTokenizer())
>>> p2 = Preprocessor(tokenizer=WordPunctTokenizer(), filters=[FrequencyFilter()])
>>> books = Corpus.from_file('bookexcerpts')
>>> friends = Corpus.from_file('friends-transcripts')
>>> %timeit -n10 p(books)
10 loops, best of 3: 411 ms per loop
>>> %timeit -n10 p2(books)
10 loops, best of 3: 437 ms per loop
>>> %timeit -n10 p(friends)
10 loops, best of 3: 4.63 s per loop
>>> %timeit -n10 p2(friends)
10 loops, best of 3: 4.98 s per loop
>>> %timeit -n10 p(books)
10 loops, best of 3: 210 ms per loop     #<- …
```
> Run FrequencyFilter only when necessary

- orangecontrib/text/corpus.py
- orangecontrib/text/pubmed.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owwordcloud.py
With desire to retain Corpus's preprocessing when passing it through Orange's widgets `__init__` and `from_table` arguments were unified with Table. Also, `from_table` and `from_corpus` were unified to `from_table` that retains preprocessing when corpus is given.
> Unify Corpus __init__ with Table

- orangecontrib/text/corpus.py
- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/wikipedia.py
Corpus now has `titles` property which returns short documents representations. This is used in Corpus Viewer in the left scrolling area — where Document 1, Document 2, ... used to be.
> Introduce Titles to Corpus

- .travis.yml
- requirements-opt.txt
- requirements.txt
Prevents installation problems on Windows (hopefully).
> Make biopython an optional dependency.

- requirements.txt
Avoid Word Enrichment crash with scipy==0.17.1.
> Request higher version of scipy

- orangecontrib/text/widgets/owloadcorpus.py
Non string attributes should not be included for text mining — they should be used as they are.
> OWLoadCorpus: Offer Only String Attrs for Text Includes

- orangecontrib/text/vectorization/base.py
This fixes SVM on sparse data.
> BoW: Mark features to skip normalization

- orangecontrib/text/widgets/owduplicates.py
When running the widget standalone the background is black. Also, occassionaly, this happens inside Orange. Assure background color is set to white.
> OWDuplicates: Assure white background

- orangecontrib/text/twitter.py
For downloading 1000 tweets this speeds the process from ~20s to ~7s. Also since Twitter limits the number of requests per time window this allows us to load more data.
> Twitter: Load 100 tweets per page

- orangecontrib/text/widgets/owcorpusviewer.py
@ajdapretnar this should enable Ctrl+C in CorpusViewer.
This fix is suboptimal since it reimplements `copy_to_clipboard` instead of "deleting" a shortcut in Widget's init (`sc = QShortcut(QKeySequence.Copy, self)`), which breaks copying from WebView.
> CorpusViewer: Enable Ctrl+C for copying

- orangecontrib/text/widgets/owpreprocess.py
When the widget was created, RegexFilter was initialized with the default pattern from the scripting part and not the value showed to the user. This PR propagated the value shown in the input field to the RegexFilter at initialization.
To reporduce, take some tweets, pass them through preprocessing with the Regexp filter on and observe tokens in WordCloud. Many characters, though listed in the filter, still remain among tokens.
> [FIX] OWPreprocess: Use regex from input, not the default one

- orangecontrib/text/twitter.py
Python's `datetime.timestamp()` assumes to represent local time while Twitter's `created_at` is in UTC. For us this caused times to be off by two hours. To fix this we now store and show the Date in UTC format.
> Twitter: Fix TimeVariable parsing

- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/utils/widgets.py
This makes Preprocessing widget a bit thinner at expense of shorter dropdowns for loading custom stopwords and lexicon.
> OWPreprocessing: Shrink FileWidget

- orangecontrib/text/widgets/owwikipedia.py
In #149 `fixed_height` argument was added to `ListEdit` which broke initialization of OWWikipedia.
> OWWikipedia: Fix ListEdit init according to #149

- orangecontrib/text/widgets/resources/wordcloud-script.js
Selection by clicking on words was broken due to use of `use strict` mode in JS and becuase the `cls` variable was declared implicitly. This threw an error `Strict mode forbids implicit creation of global property 'cls'` which broke selecting. Declaring `cls` should fix the issue.
> OWWordCloud: Fix selection by clicking

- orangecontrib/text/widgets/owduplicates.py
Show an error when only one document is present on input. Otherwise this crashed linkage calculation with `ValueError: The number of observations cannot be determined on an empty distance matrix.`
> [FIX] Duplicate Detection One Doc Error

- orangecontrib/text/corpus.py
Even when no documents are present the shapes of empty matrices should match the number of columns. Otherwise, `Table.from_table` can fail. To reproduce the bug, use Wikipedia and connect it to CorpusViewer. Search for something that will return zero documents and then in CorpusViewer click on one Search Feature. This will re-trigger `Corpus.from_documents` and the `Table.from_table` will fail with `ValueError: total size of new array must be unchanged`.
> [FIX] Corpus.from_documents: Assure Correct Shapes When no Docs

- orangecontrib/text/nyt.py
This fixed tests for Orange's versions above 3.3.8. Due to using different instaces for parsing, the instace in domain did not have `have_time` nor `have_date` attribute set which caused `repr_val` function to just return string representation of the float. To fix the problem, we now use the same instance in domain as for parsing.
> NYT: TimeVariable as Class Var

- orangecontrib/text/corpus.py
`Corpus.titles` should not search for titles among bag of words features. To reproduce pass bookexcerpts through BoW and pass it to CorpusViewer. Since bookexcerpts contain token `title` we get counts (`0.000`, `1.000`, etc) as document titles instead of the default `Document {}` titles.
> [FIX] Corpus.titles: Skip BoW features

- orangecontrib/text/widgets/utils/widgets.py
With Python 3.5 and PyQt5 emmiting either `str` or `None` seems to cause segfaults. Hence, emmit empty string instead of `None`.
> [FIX] FileWidget: Fix `on_open` Signals for PyQt5 on Python 3.5

- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_nyt.py
Changes:
* Fix sleep issues and set sleep time to 1s as the default rate limit is one request per second.
* Skip HTTPErrors with code 403 (Forbidden) — which occasionally happen just for some page numbers — and continue loading other pages.
> NYT fixups

- orangecontrib/text/widgets/owcorpusviewer.py
When selecting multiple documents they are now in one single table so that columns are always of equal width.
> OWCorpusViewer: Align multi docs table columns

- requirements.txt
A friendly reminder not to forget bumping Orange version before the next release.
PRs that need the new version:
- #139 since due to a bug fixed in https://github.com/biolab/orange3/pull/1675
> Requirements: Bump Orange version

- orangecontrib/text/widgets/owgeomap.py
When counting locations each document can contibute at most one for each country desipte how many times the location is repeated inside the document's location attribute.
> [FIX] OWGeoMap: Remove duplicates per doc

- doc/conf.py
- doc/index.rst
- doc/scripting/async.rst
- orangecontrib/text/twitter.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/owwikipedia.py
- orangecontrib/text/widgets/utils/__init__.py
- orangecontrib/text/widgets/utils/concurrent.py
As we discussed with @janezd during my visit it's not a good idea to inherit `OWConcurrentWidget` from `OWWidget` and better to make something like `OWConcurrentMixin`. It's not easy though 😄 
Here is a slightly different approach. I moved all functionality into a decorated method, so no inheritance is needed at all.  
Here is an example: 
``` python
from orangecontrib.text.widgets.utils.concurrent import asynchronous
from PyQt4.QtCore import QObject
import time
class Widget(QObject):
def __init__(self, name):
super().__init__()
self.name = name
@asynchronous
def task(self):
for i in range(5):
time.sleep(0.5)
self.report_progress(i)
return 'Done'
@task.on_result
def report_result(self, result):
print('`{}` result: {}'.format(self.name, result))
@task.callback
def report_progress(self, i): …
```
> asynchronous redesign

- orangecontrib/text/tests/test_utils.py
- orangecontrib/text/util.py
- orangecontrib/text/widgets/owwordenrichment.py
- requirements.txt
OWWordEnrichment that crashed with version 0.17.1 of Scipy was reformatted to also work on 0.17.1 hence the version pinning is not required any more.
Pinning the version to 0.18.1 caused some problems with installation on Windows which should now, hopefully, be resolved.
> Scipy: Remove pinned version

- orangecontrib/text/widgets/ownyt.py
With refactor of @asynchronous error reporting was broken for NYT. For example, run Search without an api key or with empty query. Instead of showing an error message the code will break somewhere.
> [FIX] OWNYT: Fix Error Reporting

- orangecontrib/text/corpus.py
Indices were reinitialised every time Corpus.from_table was called. Use old indices instead.
> [FIX] Corpus.from_table: Retain instance indices

- orangecontrib/text/tests/test_wikipedia.py
Wiki tests run live on Wikipedia and they broke a few days ago. This PR makes them a bit more robust but we should totally refactor this soon.
> Fix Wikipedia Tests

- orangecontrib/text/widgets/owcorpusviewer.py
Render images from columns with `type=image` instead of showing the url/path.
> OWCorpusViewer: Render Images

- orangecontrib/text/preprocess/filter.py
**Issue**
Stopwords were loaded with platform default encoding which can cause encoding errors (issue #175).
**Changes**
Detect encoding of the stopwords file with Orange and use it instead of the default one.
> [FIX] Preprocess: Detect File Encoding for Stopwords

- orangecontrib/text/widgets/ownyt.py
The code crashed when clicking report before running any search.
> [FIX] OWNYT: Report Query Only When Present

- orangecontrib/text/widgets/owgeomap.py
GeoMap crashes when no data is provided and the map is changed (e.g. World -> EU).
Iterator for locations is modified to iterate over data only when it is present.
> [FIX] GeoMap: Don't crash when changing map without data

- requirements.txt
Before 3.0.5 NLTK did not have TweetTokenizer that we use.
> [FIX] Requirements: NLTK >= 3.0.5

- orangecontrib/text/widgets/owwordenrichment.py
OWWordEnrichment crashes when data from Tweet Profiler is sent to it and when selection is made with Select Rows and remove unused features is on.
https://sentry.io/biolab/orange3-text-bl/issues/204513439/
Fix check for features overlap to report not overlap when only columns with nans are present.
> [FIX] OWWordEnrichment: Fix Overlap Check for All Nan Columns

- orangecontrib/text/tests/test_tweetprofiler.py
- orangecontrib/text/tweet_profiler.py
Server call can return None when servers are down which causes the code to crash.
`tweetProfiler.transform` returns None when something goes wrong.
> [FIX] TweetProfiler: Return None When Servers Down

- orangecontrib/text/util.py
- orangecontrib/text/widgets/owtopicmodeling.py
Change `Utils.chunkable` to report progress as fraction rather than the number of processed instances. Should fix https://sentry.io/biolab/orange3-text-bl/issues/210464520/ (though I'm not quite sure how this even happened).
> [FIX] Utils.chunkable: Report Progress as Fraction

- orangecontrib/text/widgets/owcorpusviewer.py
In CorpusViewer scrolling didn't work on PyQt5.
Don't disable WebviewWidget when on PyQt5, since the issue will be solved in Orange. Blocked on https://github.com/biolab/orange3/pull/1983.
> [FIX] CorpusViewer: Don't Disable WebviewWidget for PyQt5

- orangecontrib/text/preprocess/filter.py
https://sentry.io/biolab/orange3-text-bl/issues/209427889/
If Orange was started without internet connection NLTK data was not downloaded. When the data is missing, importing anything from `orangecontrib.text.preprocess` crashed with a `LookupError` since `StopwordsFilter` assumed the data is alredy downloaded.
Use empy list as a list of supported stopwords languages in `StopwordsFilter` when NLTK data is missing.
> [FIX] StopwordsFilter: Don't Crash When no NLTK Data

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owgeomap.py
- orangecontrib/text/widgets/owwordcloud.py
QWidget instances should not be used as WebViewWidget's bridges. This results in log messages like:
`Property 'X'' of object 'OWWordCloud' has no notify signal and is not constant, value updates in HTML will be broken!`
Change CorpusViewer, GeoMap and WordCloud to use QObject classes as bridges instead.
> [FIX] Use QObject Classes as WebView Bridges

- .travis.yml
- .travis/install_pyqt.sh
- .travis/util.sh
- setup.py
PyQt was not yet installed on Travis.
* Install PyQt to enable widget tests.
* Run tests on PyQt5.
* Change `setup.py tests` to discover tests instead of hardcoding its location.
> [MNT] Install PyQt on Travis to Enable Widget Tests

- README.md
Since Orange3-Text is on Anaconda installation process is a bit simpler.
> README: Update Installation Instructions for Anaconda

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_concordances.py
Documents were colored by document index, instead of matching documents. This caused several documents to be colored the same.
> owconcordance: Proper coloring of documents

- orangecontrib/text/widgets/owgeomap.py
In text we use empty strings for missing string attributes, while WB Indicators sometimes uses `None`. 
https://sentry.io/biolab/orange3-text-bl/issues/219723298/
Modify `_iter_locations` to skip `None`.
> [FIX] GeoMap: Skip Nones in _iter_locations

- conda_environment.yml
- orangecontrib/text/misc/environ.py
Documentation for the scripting part did not properly build on RTD.
Install PyQt with conda and not pip. Assure `nltk_data_dir` exists.
> [FIX] Fix Scripting Part Documentation Building on RTD

- orangecontrib/text/corpus.py
Fixes #224.
Store reference to the original variable to compute values.
> Corpus.extend_attributes: Add parent reference to compute_values

- .travis.yml
Tests started failing for python 3.6 due to problems with PyQt4 installation. 
Temporarily disable Python 3.6 tests.
> Travis: Disable Python 3.6 Tests

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/tests/test_owworldclooud.py
WordCloud crashes on empty corpus and empty topic.
Do not plot when corpus/topic is empty.
> [FIX] Word Cloud: test and prevention empty data

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_concordances.py
Fixes #208. 
1. Concordance computes tokens internally to distinguish from corpus.tokens.
2. Input and output set to Corpus.
3. Widget doesn't crash upon deleting the connection.
> Concordance: tokenization and small fixes

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
If X is given use it no matter if it contains data or not. This is required for applying a BoW classfifer on new data. Classifiers use `from_table` (which creates a new corpus) and if no classifier's tokens appear in the new data documents, then X is an empty sparse matrix of the correct shape. In this case, we currently replaced this empty X with a sparse matrix without columns which caused classifiers to crash with shape mismatch (but only when there was no words overlap).
Corpus's `__init__` uses provided X if it is given without checking for its size.
> [FIX] Corpus: Use given X even if empty

- .travis.yml
Builds fail on py35 and PyQt4.
Remove py35 from Travis.
> Travis: Remove py35 build

- orangecontrib/text/widgets/owcorpusviewer.py
> [FIX] Corpus Viewer: selection now as ContextSetting

- orangecontrib/text/widgets/utils/widgets.py
When editing the min_df number in Preprocess Text and pressing Enter the changed values was not propagated to the filter. Hence even when changing the min_df value the number of tokens remained the same.
The bug is in `RangeWidget` who simply triggered `editingFinished` signal but did not set the new value to the master's attribute.
When editingFinished signal is triggered (e.g. when pressing Enter) the value is now updated to the master's attribute. Also we send `editingFinished` signal only when there actually was a change to the master's attributes.
> [FIX] utils.widgets.RangeWidget: Synchronize only on editingFinished

- orangecontrib/text/widgets/owwordcloud.py
When connecting an output of some widget with dynamic outputs (e.g. SelectColumns) to WordCloud it was connected as s Topic by default, since Corpus and Topic are both instances of Table.
Make Corpus a default input. Since Topic only comes from Topic Modelling widget which does not have dynamic outputs, this change causes no problems there — i.e. when connecting Topic to WordCloud is correctly connected as a Topic.
> OWWordCloud: Make Corpus a default input

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_concordances.py
#217
Save filter word as context setting and reuse it when no word on input.
> [FIX] Concordance: word settings

- orangecontrib/text/widgets/owcorpusviewer.py
If one passes data with tokens & tags, mark the checkbox to display tokens & tags and then replaces the data set with the one without tags it crashed. The problem was that `show_docs` was called before the checkbox was disabled.
Disable the checkbox before calling `show_docs`.
> OWCorpusViewer: Disable show tokens before show_docs

- orangecontrib/text/widgets/owpreprocess.py
Default for DF in Preprocess Text was meaningless as it output all the documents.
Set the new default to filter out tokens in less then 10% and more than 90% of the documents.
> Better defaults for DF in Preprocess Text

- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Fixes #265
Set `min_df` and `max_df` to `0` and `1` when filtering by frequency not selected.
> [FIX] PreprocessText: Fix frequency filtering bug

- orangecontrib/text/pubmed.py
Awkward names of features, title attribute was not set to title
Renaming, a feature with the paper name was set a title=true attribute. This identifies which feature is being displayed in the list of text documents in Corpus viewer.
> PubMed meta features had a bit awkward names

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
After https://github.com/biolab/orange3/pull/2457 using matas for `__len__` can causes problems with `from_table`. E.g. create BoW and set some of BoW features as class in Select Column and the error will be thrown. Since setter of Y calls len, and in `from_table` Y is set before metas, the setter for Y can be given the wrong length.
Not sure why we had to overwrite `__len__` in the first place, but using Table's seems just fine.
Remove Corpus's `__len__`, use Table's instead.
> Corpus: Remove __len__, use Table's __len__ instead

- orangecontrib/text/pubmed.py
- orangecontrib/text/tests/test_pubmed.py
Pubmed did not show dates correctly.
Parse dates through `TimeVariable` instance from the domain.
> [FIX] PubMed: Fix DateTime Parsing

- orangecontrib/text/corpus.py
PubMed can crash when missing values are among class variables.
`Corpus.extend_corpus` doesn't add `None` to Discrete variable values any more.
> [FIX] Corpus.extend_corpus: Remove Nones from discrete values

- orangecontrib/text/preprocess/__init__.py
- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/tests/test_preprocess.py
A preprocessor can be constructed with tokenizer=None (actually, this is the default!).
In this case preprocessing produces a single token with the complete text. This can cause many problems and is probably never desired/useful.
1. If tokenizer=None, use the same default tokenizer as is used in base_preprocessor, which is called when accessing Corpus.tokens without previous explicit preprocessing.
2. Move base_preprocessor into the preprocess.py module, right after the class Preprocess (of which it is an instance).
> [FIX] preprocess: Use default tokenizer when None

- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
One cannot convert Orange's data table to Corpus instance.
* `OWCorpus` now has `Table` input. When present, some GUI elements are frozen and the data from the input is considered.
* Raise an error when corpus has not textual features.
* Raise an error when no text features are selected.
* CorpusViewer now accepts Corpus, not Table.
> [ENH] Add Table Input to Corpus

- doc/widgets/corpusviewer.rst
- orangecontrib/text/widgets/owcorpusviewer.py
After renaming CorpusViewer input from Data to Corpus, old schemas couldn't be loaded any more.
Mark that Corpus input replaces the old Data input.
> CorpusViewer: Corpus input backwards compatibility

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_concordances.py
> [FIX] Concordance: selection settings

- orangecontrib/text/widgets/owtopicmodeling.py
Topic Modelling crashes when there is no Corpus.
> [FIX] Topic Modelling: do not call get all topics table when no corpus

- requirements-opt.txt
- requirements.txt
Biopython failed to install without proper compiler.
Since version 1.70 they included pre-compiled binary wheel packages on PyPI for Linux, Mac and Windows.
source: https://github.com/biopython/biopython
Add biopython library to requirements. Pubmed widget is now available without manually installing biopython.
> Move biopython back to requirements

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
> [FIX] Corpus: remove text features which not in metas

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/utils/widgets.py
PreprocessText has issue reading stopwords files with incorrectly-detected encodings, such as [stopwords-sl2.txt](https://github.com/biolab/orange3-text/files/1511028/stopwords-sl2.txt).
Try UTF-8, system encoding, and detected encoding in succession. If all fails, warn politely.
> PreprocessText: handle encoding errors reading stopwords/lexicon files

- orangecontrib/text/corpus.py
- orangecontrib/text/vectorization/base.py
BoW features when comming from compute values were dense, when some features already existed in the corpus. The core of the problems is bad logic for deciding on the sparsity, which was fixed in https://github.com/biolab/orange3/pull/2341 and released in `Orange=3.8.0`.
* Remove the preference for sparse matrix when X is empty.
* Mark all BoW features as sparse — this assures that X becomes sparse even when data comes from compute values.
* This also fixes the currently failing tests on the master which failed due to updates in `Orange=3.8.0`.
**IMPORTANT:** Orange version in `requirements.txt` wasn't bumped to `3.8.0` on purpuse and the code was written in a backwards comparible manner so that the addon can also work with older versions of Orange. Note, however, that it is higly …
> [ENH] Corpus & Bow: Improve sparsity handling according to Orange>=3.8.0

- orangecontrib/text/corpus.py
Sometimes a `corpus` is created which has integer types numpy arrays.
See here:
Make sure that a new created array is type `float64`.
> [FIX] Corpus: X and Y arrays must always be float!

- orangecontrib/text/widgets/owpreprocess.py
The FileWidget used in the FilteringModule class of owpreprocess allows opening files with a .txt extension only. The stopwords files included with the nltk_data do not have this extension. So these files nor any other files lacking a .txt extension can be selected as files for Stopwords or Lexicons.
Fixes https://github.com/biolab/orange3-text/issues/333.
This change adds a selector for "All files" in addition to "Only text files" in the FileWidget creation for the FilteringModule class. 
The documentation describes creating files from scratch with a .txt extension, which is still appropriate, so no documentation changes are needed. No tests cover the FileWidget dialogs used by the FilteringModule.
> owpreprocess: Add choice in FilteringModule for All Files (*)

- orangecontrib/text/vectorization/bagofwords.py
Using gensim==3.4.0
```
======================================================================
ERROR: test_binary (orangecontrib.text.tests.test_bowvectorizer.BowVectorizationTest)
----------------------------------------------------------------------
File "/home/travis/build/biolab/orange3-text/orangecontrib/text/tests/test_bowvectorizer.py", line 22, in test_binary
result = vect.transform(corpus)
File "/home/travis/build/biolab/orange3-text/orangecontrib/text/vectorization/base.py", line 17, in transform
return self._transform(corpus, source_dict)
File "/home/travis/build/biolab/orange3-text/orangecontrib/text/vectorization/bagofwords.py", line 78, in _transform
X = matutils.corpus2csc(model[temp_corpus], dtype=np.float, num_terms=len(dic)).T
File …
```
> [FIX] bagofwords: Use vectorized 'BINARY' local weighting

- requirements.txt
> 'typing' requirement is only for python<3.5

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/widgets/owpreprocess.py
Fixes #351 
Get existing stopword files when widget is loading and not before they are downloaded.
> [FIX] OWPreprocess: no stopword files on win

- orangecontrib/text/guardian.py
- orangecontrib/text/tests/test_guardian.py
Fixes #354 
The `test` key has a limit we exceeded so the tests failed. This is resolved by requesting a developer  API key. Because it's a secret we add it to Travis as an environment variable (THE_GUARDIAN_API_KEY).
> [FIX] guardian: fix failing tests

- orangecontrib/text/widgets/owcorpusviewer.py
Long URLs cause the horizontal scroll bar in CorpusViewer.
Break more.
> CorpusViewer: Break long urls

- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpubmed.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/owtweetprofiler.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/owwikipedia.py
- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/utils/owbasevectorizer.py
Fixes #350.
Remove redundant report buttons as we now have footer report.
Add report functions where they don't yet exist.
Add __main__ calls for testing widgets.
Don't know how to add word cloud to report. report_plot doesn't work as there is no <svg> tag in the constructed html. report_raw works, but places the word cloud over existing text and remains selectable.
Don't know how to make the header of Word Enrichment bold. 🤦‍♂️ 
Don't know how to shorten QTableView in Concordance to show only, say, top 50 results. I read about QSortFilterProxyModel, but I don't know how to set the number of rows.
> Improve report functionality

- orangecontrib/text/guardian.py
Fixes #359 
A credential is valid only if the API response code is 200.
> [FIX] guardian: credential is valid only if the API response is OK

- orangecontrib/text/widgets/owwordcloud.py
WordCloud's report contains only the frequency list of words and not the nice word cloud picture.
Adding the picture with `report_plot(self.webview)` results in an image at the top of the report that overlaps other content.
Augment the html with a div of appropriate height to compensate for the absolute positioning of span objects of individual words in the webview's html.
Depends on https://github.com/biolab/orange3/pull/3148.
> OWWordCloud: Add the word cloud image to the report.

- orangecontrib/text/guardian.py
- orangecontrib/text/tests/test_guardian.py
- orangecontrib/text/widgets/owguardian.py
TheGuardianAPI would crash if requests limit is exceeded. The exception was not informative because it's raised further in the request processing.
Now an informative exception is raised. Additionally, this helps with the falling test which is now skipped if this error is raised.
> Guardian request limit exceeded

- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- requirements.txt
Partially implements #298.
Add [UDPipe](http://ufal.mff.cuni.cz/udpipe) Lemmatizer to preprocessing.
> [ENH][WIP] Add UDPipe Lemmatizer

- orangecontrib/text/widgets/__init__.py
Directs docs to https so that they always appear in canvas.
See https://github.com/biolab/orange3/issues/3247 and https://github.com/Quasars/orange-spectroscopy/pull/216.
> Documentation can appear in canvas

- orangecontrib/text/twitter.py
Fixes #388.
Updated retrieval of Author timelines to fit the new API.
> Fix retrieving Author timeline

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/resources/wordcloud2.js
Fixes #347 
Scale font size in proportion to the window size.
> [FIX] OWWordCloud: scale visualization

- .travis.yml
This add-on run tests on Python 3.4 and 3.5. As core Orange3 now only test on 3.6 it's appropriate to change the testing hear as well.
Update Travi python version.
> [ENH] Travis: update Python version

- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/tests/test_owduplicates.py
Fixes #378. 
Detect Duplicates now outputs correct documents with Duplicate Cluster output.
> Output corresponding duplicate cluster

- orangecontrib/text/misc/nltk_data_download.py
The nltk package prints download status which can be annoying. 
Silence the prints.
> [ENH] nltk: disable download prints

- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/topics.py
Fixes #411
gensim>=3.7.0 changed HdpModel.show_topics() behavior when using num_topics=-1 ([issue](https://github.com/RaRe-Technologies/gensim/issues/2389))
Replace -1 with number of topics.
> [Fix] topics: HdpModel showing no topics

- doc/widgets/preprocesstext.rst
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/utils/widgets.py
Fixes #418 
Changin tagger file loding.
> [FIX] OWPreprocess: fix Stanford tagger loading

- .travis.yml
Traivs test fails due to too many static dependencies
- Changed dist to Ubuntu Xenial (longer cache for dependencies).
- Added tests for Python 3.7.
- Removed PyQt5 from env since all builds use PyQt5.
> Travis changed dist to Xenial (Ubuntu 16.04)

- orangecontrib/text/widgets/utils/concurrent.py
#420 #421 
The problem occurs due to multithread communication using `QMetaObject.invokeMethod` with a destroyed object.  Wrapping up all invoke calls with try/except will suppress errors.
It seems like there is no _simple_ way to know that C++ `QObject` is about to be destroyed so I wasn't able to find other reliable solutions.
> Suppress multithread communication errors 

- orangecontrib/text/tests/test_wikipedia.py
- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/tests/test_owduplicates.py
Tests fail.
Two small fixes that make the test pass.
1. Replace assertEquals with assertEqual. This did not break the tests, but it did issue a warning.
2. Set smaller minimum width in Duplicates. Tests failed before because of the new version of Orange which enforced minimum widget width.
> [FIX] Fix failing tests

- orangecontrib/text/stats.py
- orangecontrib/text/tests/test_stats.py
- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owwordenrichment.py
Replace local implementation of FDR with core Orange's implementation.
Import FDR from Orange.
> [WIP] Replace local FDR with Orange's

- orangecontrib/text/import_documents.py
Fixes #426.
Remove NULL bytes from pdfs.
> [WIP] Import Documents sanitizes pdfs

- orangecontrib/text/widgets/owpreprocess.py
Tests failed with AssertionError, because the width of Preprocess Text was too big.
Decrease widget width.
> Preprocess Text: decrease width

- requirements.txt
Google compute engine was added as a requirement because Travis test was failing because of issues with boto. The issue is still present but since google-compute-engine is not available on Windows it must be installed only on Linux and Mac OS.
Google compute engine is limited to Linux and Mac OS.
> Remove google compute engine

- orangecontrib/text/nyt.py
- orangecontrib/text/pubmed.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/ownyt.py
Current merging of https://github.com/biolab/orange3/pull/3772 caused import issues in the add-on.
Replace imports with new ones.
> Compatibility with split canvas

- .travis.yml
- requirements.txt
`google-compute-engine` was added to the package to solve travis issues with `boto` library. 
With this PR I am trying to remove google-compute-engine since it is preventing us to make conda-forege package OS independent. https://github.com/conda-forge/orange3-text-feedstock/pull/26
> Test remove google-compute-engine

- conda_environment.yml
- orangecontrib/text/pubmed.py
- orangecontrib/text/tests/test_pubmed.py
- orangecontrib/text/widgets/owpubmed.py
- requirements.txt
Fixes #440
With this pull request we:
- remove valiate_email dependency from the add-on - it is now checked with regex in the widget
- save email through CredentialManager
> Remove validate email

- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
Even though this will fix the issue with pickling `UDPipeLemmatizer` the fact that `Corpus.used_preprocessor` is traveling around up to `Network from Distances` is quite suspicious. 
`updipe.Model` is not compatible with pickle protocol thus should be manually loaded.
> Pickling UDPipe #387

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Extend function is no longer available in Orange - consequently it does not work in Text anymore. 
Since it is not available in Orange anymore I suggest removing it in Text too. I do not find any usage of this function within the add-on. The deprecation message was already appearing to users since Orange's extend was called.
> [FIX] Remove extend function from corpus

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
Fixes #455 
- Stopwords are now correctly removed - I removed the whitespace on the end of each word in the dictionary
- Languages in stopwords dropdown are now sorted in alphabetical order
> [FIX] Fix stopwords filtering

- doc/widgets.json
Add widget.json for displaying documentation on the webpage.
Built with:
```
python ~/orange/orange-hugo/scripts/create_widget_catalog.py  --categories "Text Mining" --doc .
```
> Json for documentation

- orangecontrib/text/widgets/owwordcloud.py
Partially fix #204 
I remove one `_new_webview()` out of `_create_layout()`.
From my understanding, `handleNewSignals()` calls either `_apply_topic()`, `_apply_corpus()`, or `clear()`. The latter directly calls `_new_webview()` while the first two call `_repopulate_wordcloud()` and then `on_cloud_pref_change()` which calls `_new_webview()` in the end. So, calling `_new_webview()` in `_create_layout()` is unnecessary and actually redundant.
> Remove a redundant web view

- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/owwikipedia.py
`processEvents` was deprecated and is already removed in orange-widget-base (https://github.com/biolab/orange-widget-base/commit/513a926901e226b6e9525a72f52a0ae0e23e8fd7), which will cause crashes once the versions are bumped.
Remove the setting of argument. All of them were set to `None` currently anyway.
> Remove uses of deprecated 'processEvents' argument

- requirements.txt
ufal.udpipe-temp is in requirements since it didn't compiled correctly at macos.
It seems it can be removed now since authors made a new release which adds missing compile requirements for macOS. I tested that on my macOS and it works correctly.
> Remove ufal.udpipe-temp

- requirements.txt
Pip does not correctly resolve dependencies of dependencies so we have version conflicts.
Problematic is botocore (from boto3 from smart-open from gensim) which has some upper bounds on package versions.
Set upper bounds in requirements.txt so that they are properly resolved.
> requirements: fix botocore dependency

- .travis/build_doc.sh
- conda_environment.yml
When new documentation is added, widget.json needs to be updated, too.
Add script to automatically check documentation updates.
> Script for automatic doc testing

- requirements.txt
Fixes https://github.com/biolab/orange3-text/issues/471
`ufal.udpipe` is replaced with `ufal.udpipe-temp` until authors do not provide wheels for the package. We now use `ufal.udpipe-temp` since it has wheels for mac. Wheels for windows would be great but users mainly use conda on windows while mac distribution of Orange uses pip by default.
> ufal.udpipe replaced with ufal.udpipe-temp until authors provide wheels

- .travis.yml
- orangecontrib/text/widgets/owsentimentanalysis.py
- requirements.txt
Orange3-text do not work at versions <3.21.0.
Define minimal orange3 version to 3.21
> Limit Orange version to lowest that orange3-text supports

- requirements.txt
Since we do not support python <3.6 anymore typing dependecy can be removed.
Removing typing dependency which comes with python in python >=3.5
> Remove typing as a dependency

- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
Fixes #213. 
Save a selection and load it upon reloading a workflow.
~TODO: solve the issue of tests.~
> Topic Modeling: save selected topic as schema_only

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
When the corpus is loaded from a file or made out of the data table, the title attribute is not set if it does not exist in data already.
With this PR we:
- implement the dropdown to select the title attribute
- implement the strategy to select the most suitable title attribute by default
- add unit-tests
When this PR is checked I will update the documentation since new images must be made.
This PR also does not address the numbering of documents in a Corpus Viewer it will be solved in a separate pull request https://github.com/biolab/orange3-text/issues/482.
> [ENH] Corpus: add title attribute selection dropdown

- requirements.txt
When authors provided wheels for ufal.udpipe I forgot to change from ufal.udpipe-temp back to ufal.udpipe. 
Changing requirement ufal.udpipe-temp to ufal.udpipe, since package now provides mac wheels.
> Change ufal.udpipe-temp to ufal.udpipe

- .coveragerc
When I write a test for a widget I cannot access the coverage. I understand that the coverage for widgets was omitted since they are not well covered, but anyway it helps if one can access the coverage for widgets too.
With this PR I suggest including widgets in coverage. What do you think @ajdapretnar?
> Include widgets in coverage

- doc/widgets/wordcloud.md
- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/tests/test_owworldcloud.py
Bag-of-words weights should be shown in the Word Cloud widget. When TF-IDF is used bag-of-words weights should better highlight the importance of the word. It was also discussed at the last meeting.
With this PR bag-of-words, weights are used in the Word Cloud widget when available.
> [ENH] Word Cloud: Show bag of words weights when bag of words features available

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpus.py
Fixes https://github.com/biolab/orange3-text/issues/482
- Now titles are stored in the corpus and subsampled together with the corpus.
- Functionality to set tile is moved from widget to corpus.
> [ENH] Corpus: Store titles in corpus to match between Corpus Viewer even when subsampled

- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
Fixes https://github.com/biolab/orange3-text/issues/479
Since I think (correct me if I am wrong) that PerfectDomainContextHandler is not needed here, I changed it to DomainContextHandler.
> [ENH] OWCorpus: Use DomainContextHandler

- orangecontrib/text/topics/topics.py
- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/resources/wordcloud-script.js
- orangecontrib/text/widgets/resources/wordcloud2.js
- orangecontrib/text/widgets/tests/test_owworldcloud.py
Fixes https://github.com/biolab/orange3-text/issues/399
Fixes #225 
Fixes #390 as much as possible
With this PR I made various fixes in the word cloud widget:
- updated the wordcloud.js library
- Addressed extra space in the projection
- Words with smaller weights do not disappear anymore
- The issue from #390 is addressed but not fixed completely. On resize, word cloud must replot, since the distribution of words on canvas must change (otherwise it would look weird). Now words keep the same color after replot.
- Words still overlap and draw one inside each other, this must be fixed in the library. I cannot do any temporary fix.
- Weights that are negative for the topic are now treated as positive in the cloud visualization #225 and colored orange when negative and green when positive …
> Various fixes in word cloud (spacing, library update, ...)

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
from_numpy in Corpus does not define titles of the documents - functions that need acess to _titles attribute fails.
from_numpy in Corpus call function that defines titles.
> [FIX] from_numpy must define titles

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
`from_list` and `from_table_rows` do not define titles, this lead to error when preprocessing is used.
Reimplemented `from_list` and `from_table_rows` such that they define titles.
> Corpus: fix - from_list and from_table_rows do not define titles

- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owwordenrichment.py
#221 
Besides implementing the thread computation with ConcurrentWidgetMixin which fixes #221, this PR also:
- implements input and output info in a status bar
- adds better unit tests for a widget
- refactors a code a bit
> Word Enrichment: Computing in a separate thread (with ConcurrentMixin)

- orangecontrib/text/widgets/utils/owbasevectorizer.py
- orangecontrib/text/widgets/utils/tests/test_owbasevectorizer.py
Fixes #498.
Add a checkbox to set 'hidden' attribute of attributes to True. Added to the base widget, so now both Bag of Words and SimHash use this option.
> Bag of Words: add option to show bow features

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/tests/test_owworldcloud.py
https://github.com/biolab/orange3-text/issues/500
- Words with a bag of words below or equal zero are removed from the word cloud. Those are words that exist in the table but does not exist for the selected text.
- Small optimization of extracting bow features
- Test fix to be robust on computational error (instead of 2. number is 1.99999999999999999).
- Rounding numbers in the list on the same number of decimal spaces (0 when all whole numbers, 2 when float numbers).
> Word Cloud: Remove words with zero weights from word cloud

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/tests/test_owworldcloud.py
When selecting documents in the data table, the Word Cloud widget was blocking main thread -- user could not smoothly select documents.
When several longer documents the counting of words can take up to a few seconds. The counting is now moved to the separate thread - with concurrent mixin.
> Word Cloud: Run counting in new thread

- orangecontrib/text/corpus.py
from_documents fail since it makes unallowed operation whichis prhibited with current changes in variable constructor.
Removed part of code that does not make harm. It is a temporary fix. We still need to simplify a corpus.
> [FIX] Corpus: remove unnecessary empty values - it is not allowed anymore

- doc/conf.py
Documentation was not properly built with the CommonMarkParser being deprecated.
Use recommonmark parser.
> Remove deprecated parser

- requirements.txt
Fixes https://github.com/biolab/orange3/issues/4730
NLTK 3.5 has regex as a dependency that does not provide macOS wheels. :( Until wheels are available we need to limit the version.
> Limit NLTK version

- orangecontrib/text/tweet_profiler.py
- orangecontrib/text/widgets/owtweetprofiler.py
Current implementation of Tweet Profiler runs in the main thread preventing user from working while the widget is running.
- Added concurrent mixin.
- Added cancel button.
> TweetProfiler: Run in separate thread

- orangecontrib/text/preprocess/normalize.py
Fixes #519 
The issue was that we were using HTTP and when 404 happened the internet provider can replace 404 responses with something else. It can be avoided with https
> [FIX] Update ulr to use https for udpipe models

- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
- Widget is locking controls while embedding. It is not required since we can easily cancel embedding when control is changed.
- The widget does not embed on new data when auto-apply is off - it is different than in other widgets (e.g. distances)
- Widget changed to not lock controls anymore
- Widget changed to always commit on new data
> Document Embedding: do not lock controls, always commit on new data

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
Currently, every time the `titles` property is accessed, the `tolist` method is called on numpy array. This operation can be relatively slow for large corpora (0.7s for friends-transcripts) and can slow down widgets that access the property many times (with this PR, the Concordance widget is approximately 500 times faster on several examples I tested it on so this partially fixes #522).
Numpy array `_titles` is converted to list only once  (inside `_set_unique_titles`) instead of every time the property is accessed.
> Corpus: Fix titles property

- orangecontrib/text/widgets/owtwitter.py
In tweeter widget, errors are sometimes not shown
Move error clearing out of the thread. This way it is assured that errors are always cleared before new errors are shown.
> [FIX] Twitter: Fix errors

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Corpus fails when indexing with range, which is not uncommon in Orange.
Support range as an indexing option.
> Corpus: add range indexing

- requirements.txt
pdfminer3k got removed from PyPI later other group forked and republished the same package but with wrong dependency list: ply is missing. https://github.com/canserhat77/pdfminer3k/issues
This was the reason why import documents widget is missing when the addon is installed.
Temporary add ply as an orange3-text dependency until pdfminer3k fixes dependency list.
> Temporary fix: add ply as an orange3-text dependency

- requirements.txt
Botocore lifted the minimal version of python-dateutils
Raise the python-dateutils version to <3.0.0
> Raise python-dateutils version

- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/lda.py
- orangecontrib/text/topics/lsi.py
- orangecontrib/text/topics/topics.py
- orangecontrib/text/widgets/owtopicmodeling.py
Fixes https://github.com/biolab/orange3/issues/4877.
Topic Modeling output matrix of dtype float32, which caused HeatMap to crash.
Cast matrix to float64.
Set explicit SizeHint to remove deprecation warning.
> Topic Modeling: set dtype of models to float64

- orangecontrib/text/corpus.py
- orangecontrib/text/sentiment/__init__.py
- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_sentiment.py
- orangecontrib/text/tests/test_vectorization_base.py
- orangecontrib/text/topics/topics.py
- orangecontrib/text/tweet_profiler.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/vectorization/simhash.py
- orangecontrib/text/widgets/owstatistics.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
- orangecontrib/text/widgets/tests/test_owworldcloud.py
- orangecontrib/text/widgets/utils/owbasevectorizer.py
When corpus is extended variable name uniqueness is not assured
- Make new variable names unique when adding corpus
- Change `extend_attributes` to return a new copy of the corpus
> Corpus: make variables name unique when extending

- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/tests/test_preprocess.py
Fixes https://github.com/biolab/orange3/issues/4905
Copy corpus.ids when preprocessing.
> [FIX] Preprocess: Retain corpus ids

- orangecontrib/text/corpus.py
Fixes https://github.com/biolab/orange3-text/issues/561
> [FIX] Corpus: fix deprecated use of array

- requirements.txt
- simhash got rid of gmpy2 in >=1.11, so dependency can be unfixed.
- pdfminer got fixed and ply is not necessary anymore
> Dependency update

- orangecontrib/text/import_documents.py
- orangecontrib/text/widgets/tests/data/good/sample_txt.txt
- orangecontrib/text/widgets/tests/data/good/sample_txt_ž.txt
- orangecontrib/text/widgets/tests/test_owimportdocuments.py
Filename (and potentially text too) can contain characters that are written in decompose form (č is composed as a char c and separate caron). It causes problems when we filter documents (user inputs č as precomposed Unicode char).
With this PR text is normalized (all decomposed chars are changed to precomposed) before outputted from the widget
> [FIX] Import documents: normalize imported text and file names

- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
Hopefully fixes https://github.com/biolab/orange3-text/issues/571
In my case, the problem is that some documents are too long and we limit the maximum length of the document that can be sent to the server. In those cases, a runtime error is raised.
With this PR:
- we enable that only documents that re too long are skipped and that embedding process is not interrupted than before
- we add a signal to the widget that shows the skipped documents - similarly than in Image Embedding widget
> Document embedder handle skipped and long documents

- orangecontrib/text/widgets/owstatistics.py
- orangecontrib/text/widgets/tests/test_owstatistics.py
- Statistics: division by zero #573
- fixed the bug on line 233 (function perc_unique) in orangecontrib/text/widgets/owstatistics.py
- _Included_ conditional check of the tokens
> fixed ZeroDivisionError on line 233 in perc_unique

- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/widgets/owdocumentembedding.py
Document embedders currently support only three languages.
With this PR we add support for 28 additional languages.
> [ENH] Document embedders: additional languages

- orangecontrib/text/vectorization/document_embedder.py
Embedder did not embed longer text due to the limit of the maximum package size.
With this PR maximal package size is increased.
I talked with Matjaz and he said the package size of 500KB is not a problem. I also tested with longer texts and it works. With this limit, the user can embed quite a long book (500 pages).
> Document Embedder: Increase maximal package size

- requirements.txt
Since `botocore` removed `docutils` dependency, we can remove it too. As far as I know, this dependency was there since pip did not know how to resolve the version conflict.
Removing `dcoutils` dependency fix.
> Remove docutils dependency

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Fixes https://github.com/biolab/orange3-text/issues/581
Identify and keep renamed text_feature
> [FIX] Corpus - from_table: keep text feature when renamed

- orangecontrib/text/vectorization/simhash.py
Smash slightly changed behaviour of the `Simhash` class in the version 2.0.0. The constructor does not handle `None` as a `hashfunction` parameter anymore.
Change call such that when `hashfunction` is None, the parameter is not passed and so the default parameter is used.
> [FIX] Simhash: Fix error when hash function is None

- requirements.txt
Reverts biolab/orange3-text#523
Regex now provide wheels for MacOS, I think it can be reverted now
> Revert "Limit NLTK version"

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Extend attributes creates a new corpus but do not retain preprocessing.
Fix extend attributes to retain the preprocessing.
> [FIX] Corpus: extend_attributes retain preprocessing

- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Fixes #597
Add a radio button to distinguish between relative and absolute frequency option.
> [FIX] Preprocess: Filter by absolute frequency

- orangecontrib/text/sentiment/__init__.py
- orangecontrib/text/sentiment/filter_lexicon.py
- orangecontrib/text/tests/test_sentiment.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
Implements SentiArt for extracting sentiment for literary texts.
Based on #609.
Add SentiArt.
Make SentimentDictionaries a base class and derive MultilingualSentiment and SentiArt from it.
Tests.
> [ENH] Sentiment Analysis: Add SentiArt method

- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/topics.py
All topic output cast topic probabilities as strings, but the variable was declared as continuous. Caused issues downstream.
Cast metas to object, which keeps topic probabilities as floats.
> Topic Modelling: Topic probabilites have to be floats

- orangecontrib/text/topics/lsi.py
In current implementation we insert update function in between add_documents call with:
```
models.LsiModel.update = models.LsiModel.add_documents	
models.LsiModel.add_documents = lambda self, *args, **kwargs: self.update(*args, **kwargs)
```
It causes problems when a module that does it is imported multiple time. In the first import `update` points to `add_documents` function in the Lsi module and it is ok. In the second import happens that `update` points to previously change `add_documents` which then recursively call itself.
It was working but is dangerous in cases when this module is imported multiple times.
Implementing the same behaviour with the inheritance - safe to multiple imports since we do not change the base module.
> LSI fix add_documents function update

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
Fixes https://github.com/biolab/orange3-text/issues/625
- Fix from_numpy which didn't initialize text_features and other variables correctly
- The Corpus widget showed an error when the `text_features` list was empty and didn't initialize Used and unused features fields. Fix to initialize fields anyways. Now error only present when no text features in the domain
- Remove deprecated `addSpace` attribute in widgetBoxs.
> [FIX]Corpus fix from_numpy and from_list; modify widget to work with corpuses without text_features

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpus.py
With https://github.com/biolab/orange3/pull/5309 include variable attributes are bool and not strings anymore. It breaks `_infer_text_features` that does not recognize attributes with `include = True`.
Fix `_infer_text_features` to handle both string and bool `include` attribute.
> [FIX] Fix infer text features

- orangecontrib/text/widgets/owpreprocess.py
The Preprocess widget will start crashing once https://github.com/biolab/orange3/pull/5308 is merged.
> Preprocess: Automated summaries compatibility

- orangecontrib/text/import_documents.py
- orangecontrib/text/tests/test_import_documents.py
- orangecontrib/text/widgets/owimportdocuments.py
- requirements.txt
- introduce URL reader
- add `URL` option to `Import Documents` widget
> [ENH] Import documents: Import from URL

- orangecontrib/text/stats.py
- orangecontrib/text/tests/test_stats.py
- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owwordenrichment.py
Word enrichment is slow when  handling datasets with many tokens
This PR speeds up the hypergeometric test such that it computes all p-values with one call instead of calling hypergeom function for each word
Speedup:
17.5s -> 0.018
21.7s -> 0.243
> Word enrichment - hypergeometric test speedup

- orangecontrib/text/keywords/__init__.py
- orangecontrib/text/keywords/embedding.py
- orangecontrib/text/tests/test_keywords.py
This PR adds a new method to extract keywords based on document embedding - word embedding similarity. 
The method is currently a bit slow on the first run (when embeddings are not cached) - it will be improved with better embedding which will send multiple words per request.
> New method - embedding keywords

- orangecontrib/text/import_documents.py
- orangecontrib/text/tests/test_import_documents.py
Since now Orange's UrlReader encodes special characters in URL https://github.com/biolab/orange3/pull/5412, special characters are getting encoded two times in import document which makes escape characters encoded and so it produces the wrong URL.
Because of changes also `self.path` is quoted and so matching with metadata fails.
- Since it is still required to keep encoding in import documents' reader to support older versions of Orange, I propose to decode and encode URLs again. If URL is not encoded, decode does not change the URL.
- Fix matching with metadata with storing non-encoded path
> Import documents - prevent double quoting

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
Fixes #658.
Add an additional output that matches the "Data" output in selection widgets in Orange.
The column adds a meta attribute denoting whether a row was selected or not.
> OW Corpus Viewer: Add annotated corpus output

- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
UDPipe lemmatizer is not picklable after first call since udpipe.Model is not picklable. The authors decided that they will not support pickling for the model.
Drop model from __dict__ while pickling
> UDPipe lemmatizer - make it picklable

- orangecontrib/text/widgets/owconcordance.py
- orangecontrib/text/widgets/tests/test_owconcordances.py
Fixes https://github.com/biolab/orange3-text/issues/660
Now searching for concordance, which is the operation that blocks the main thread, is performed in the separate thread with ConcurentMixin.
> Concordance - search in the separate thread

- orangecontrib/text/widgets/owscoredocuments.py
Widget tried to find words from any variable
The widget should look only for StringVariables. It matches the keywords widget behaviour
> Score documents - search words among string vars

- orangecontrib/text/widgets/owscoredocuments.py
Score documents widget is slow on a corpus that is not preprocessed since `corpus.tokens` is called regularly and each time they are regenerated when the corpus is not previously preprocessed by the preprocess widget
Call `corpus.tokens` only once per scoring.
> Score documents - speedup slow scorer on non-preprocessed documents

- orangecontrib/text/keywords/__init__.py
- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/tests/test_owkeywords.py
`Embedding` scoring method is missing in the `Keywords` widget.
Add `Embedding` scoring method to the `Keywords` widget.
> [ENH] Keywords: Add 'Embedding' scoring method

- orangecontrib/text/preprocess/preprocess.py
- orangecontrib/text/tests/test_preprocess.py
With the recent conllu reader (#675) one could import just POS tags without lemmas. We allow the user to do that, but in Preprocess Text tags would be used with new tokens, which causes severe mismatch. 
Reset POS tags when running tokenization.
This would also solve issues with the wrong ordering.
> Preprocess: Reset tags on tokenization

- orangecontrib/text/corpus.py
- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Implements #678. 
Add option to filter POS tags directly in Preprocess Text.
Add setter and getter to Corpus for easier pos_tag handling.
> OWPreprocess Text: add option to filter on POS tags

- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/lda.py
LDA is a generative model and has thus a random state that one can preset. For Orange workflows to be reproducible, we need to set a fixed random seed.
Add a fixed random seed.
Should we instead add a checkbox for reproducible LDA in the widget?
> LDA: Add random state

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
Fixes #691. POS tags were incorrectly filtered. 
When filtering tokens, assure POS tags are filtered alongside.
> Preprocess: Filter POS tags along with tokens

- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
Partially implements #665. 
Add log perplexity (for LDA) and topic coherence scores to the widget.
> Topic Modeling: Add topic evaluation scores

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
Order of the elements in the table is not remembered by Score Documents widget
Remember order as a setting
> Score documents - remember sorting

- orangecontrib/text/widgets/owtopicmodeling.py
Fixes #689. 
POS tags were shown alongside tokens when displaying top 10 words per topic.
Remove tags just for display, not for computing topics.
> Topic Modeling: Remove tags from display of topics

- doc/widgets/preprocesstext.md
- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
- requirements.txt
Expand collection of normalization models.
Adds Lemmagen to normalizers for preprocessing.
> OWPreprocess Text: Add Lemmagen normalizer

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
Score documents widget is missing selection
Implemented selection in the table view and the `Selected documents` output
> Score documents: Document selection and selection output

- orangecontrib/text/widgets/owkeywords.py
Move `Select words` box to button area to make the widget consistent with core Orange widgets.
> Keywords: Move selection box to buttons area

- requirements.txt
Gensim 4.1.0 and 4.1.1 have issue with building wheels https://github.com/RaRe-Technologies/gensim/issues/3226
It works with newset numpy but does not work with numpy used in installer - 1.19
4.0.* had issues before already 
Temporarily limiting Gensim to <4. It should be changed when they provide a working version.
> Temporarily limit gensim to <4

- requirements.txt
In https://github.com/biolab/orange3-text/pull/718 limited Gensim to <4 since text add-on stopped working on older NumPy-s
They proposed new wheels, so we can now set the version to >4.1.2
> Gensim: set version to >4.1.2 after they fixed NumPy compatibility

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
1. If Score Documents received Table as Corpus input, it crashed since all checks for corpus objects would fail (`self._is_corpus_normalized`, etc.).
2. If Score Documents received generic Table as Words input, it crashed since it tried to sort by average length, but if variables had the same average length, it would try to sort by Variable object, which resulted in a crash.
1. Return None and a Warning if input data is not of type Corpus.
2. Sort by variable name, which, if I am not mistaken, are always unique and hence `sorted()` would never get to the final tuple object, which is a Variable.
> Score Documents: Fix crashes with wrong inputs

- orangecontrib/text/preprocess/filter.py
`_filter_tokens` is called twice since it is called in `__call__` and `super().__call__()`
Removing `__call__` from subclass since filtering is handled by the super class `__call__`.
> pos tag filter: Remove __call__ from subclass

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
Fixes #741.
Ensure unique variable names on output.
> OWScoreDocuments: Ensure unique names on output

- orangecontrib/text/semantic_search.py
- orangecontrib/text/tests/test_semantic_search.py
Implements a component that communicates with semantic search API.
> Semantic search server communicator

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
Fixes #704 using Option 1.
Do not run search after every keypress (slow), but only once after typing the whole query and pressing Enter.
> Corpus Viewer: Run search when finished typing the query (on enter).

- orangecontrib/text/topics/lda.py
- orangecontrib/text/topics/topics.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
Current topic implementation train models such that they get chunks of documents at a time. For small corpora, it means that one chunk is 1 or 2 documents big. This kind of topic training also results in bad results. 
The problem with LDA is that it is usually not trained enough (all documents do not converge).
- train topic models in one shot and use callback for progress instead of training in chunks (the problem here is that only LDA supports callbacks which means that the other two models will not have progress in the widget 👎  )
- increase the number of passes and iterations for LDA - it solves the second problem from the above list (with more passes and iterations model will take more time to train than before). Setting passes to 5 is not optimal since it varies depending on the …
> [FIX] Topic - remove topic computations in chuck which results in poor topics

- orangecontrib/text/semantic_search.py
- orangecontrib/text/tests/test_semantic_search.py
1. When doing a semantic search on laws, many of them are longer than 50000, all of them are below 300000
2. Sometimes embedding fails since timeout happens in embedding. In those cases result for a chunk is None and not a list. The current implementation fails since it wants to extend the list with None.
- handle error 2
- allow documents to be maximally 300000 long and still make chunks with max size 50000. Documents that are longer than MAX_CHUNK_SIZE will be in one request which is longer thank MAX_CHUNK_SIZE
> semantic-search: increase maximal allowed chunk size, fix error when timeout

- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/vectorization/bagofwords.py
Bag of Words computed TF-IDF on new Corpus (from computing values) considering counts in new Corpus for IDF weighting. I think it should consider counts from the original Corpus for IDF. One document on the input resulted in different output than the same document in Corpus with others.
Use counts from the original Corpus for the IDF part.
> BoW: fix vectorisation to use only original weights for IDF on new data

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
In score documents, titles with newline characters were cropped and centered vertically
Remove newline characters from titles for display purpose (as table widget and corpus viewer do)
> [FIX] score-documents: handle document titles with newlines

- orangecontrib/text/widgets/owldavis.py
PyLDAvis don't work on older pyqtgraph 
Fixed import to work on older pyqtgraph version
> pyldavis - fix ItemSample import to work with older pyqtgraph

- orangecontrib/text/sentiment/__init__.py
- orangecontrib/text/tests/test_sentiment.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
Fixes #739 and another error in Sentiment Analysis.
- OWSentimentAnalysis: fixed the part of code that calls preprocessors on NoneType.  
- SentiArt: fixed the part of code that causes an error when a document doesn't contain any word from dictionary.
> Sentiment Analysis: prevent preprocessing of NoneType and computing mean of an empty array

- orangecontrib/text/import_documents.py
- orangecontrib/text/misc/nltk_data_download.py
- orangecontrib/text/tests/test_import_documents.py
- requirements.txt
- tox.ini
Orange<3.31.1 does not support numpy>=1.22. Since there is no guarantee that numpy version will be <1.22 we must increase the Orange version to 3.31.1 otherwise Orange3-text does not work. Orange3-text even trigger updating numpy since one of its dependencies needs a higher version than is packed in the Orange3 installer.
With this PR I increased oldest supported version of Orange to 3.31.1
Also:
- fix nltk incompatiblity
- remove unneeded quoting in import documents
> Increase minimum supported version of Orange to 3.31.1

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/__init__.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/topics/topics.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/widgets/owduplicates.py
- orangecontrib/text/widgets/tests/__init__.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
- orangecontrib/text/widgets/tests/test_owduplicates.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owstatistics.py
- orangecontrib/text/widgets/tests/test_owwordcloud.py
Text add-on have disabled table lock
Enable table lock and resolve all table lock incompatibilities
This PR also:
- moves clusters to metas in duplicates widget's output table (similarly than it is made in other widgets). Before it was decided by the user via combo box which is now removed
- updated Corpus.from_file to search for files in `dataset_dirs` instead of having its own logic
- deprecate `extend_corpus` since it is not compatible with the idea of not changing table, it is also not used in the add-on
- remove temporary function `get_unique_names` which can be now imported from Orange
> Table lock compatibility

- orangecontrib/text/import_documents.py
- orangecontrib/text/tests/test_import_documents.py
- requirements.txt
Import documents downloads files synchronously which is slower to asynchronous download.
Implement asynchronous download with HTTPX library.
Speedups:
predlogi-vladi-1k: 670s-> 47s
predlogi-vladi: now 540s for all documents (before more than 1h30m)
> Import documents: async url reader

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Using Filter (Regexp) one can remove tokes with numbers. This may be difficult for some users, so add new options to Filter that:
- remove tokens with numbers
- remove tokens that are numbers
> Preprocess: Filter tokens with numbers

- tox.ini
Github changed permissions without authentication. Use links that are able to reach without authentication.
> CI: Fix latest orange links

- .github/workflows/test.yml
windows-2016 workers were deprecated and removed from March 15
Replace windows-2016 with windows-2019 workers
> Replace deprecated windows-2016 with 2019

- orangecontrib/text/widgets/owsemanticviewer.py
- orangecontrib/text/widgets/tests/test_owsemanticviewer.py
> [FIX] Semantic Viewer: Put NaNs last when sorting

- orangecontrib/text/import_documents.py
Import Documents read files in a different order on different systems.
Ensure file order is always stable (sorted alphabetically).
> OWImportDocuments: ensure stable file order

- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/tests/test_owwordenrichment.py
Fixes #775. 
Handle selected data input being Table.
> OWWordEnrichment: don't crash on selected data as Table input

- orangecontrib/text/concave_hull.py
- orangecontrib/text/tests/test_concave_hull.py
- requirements.txt
This PR implements concave hull around clusters o points implementation
> [ENH] Functionalities for computing concave hull around clusters of points

- orangecontrib/text/concave_hull.py
- orangecontrib/text/tests/test_concave_hull.py
The concave hull does not work when less than 3 unique points in the cluster
When offsetting clusters min and max are used. Use global min/max instead
- concave hull works for any number of points
- use global min/max for offsetting -- produces equal offset according to whole image
> Concave hull: fix cases when less than three unique points in cluster

- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/tests/test_owkeywords.py
Fixes #806
Invoke preprocessor's `__call__` instead of `normalizer`.
> [FIX] Keywords: Always invoke preprocessor __call__

- orangecontrib/text/concave_hull.py
- orangecontrib/text/tests/test_concave_hull.py
When all points of the polygon are inline offsetting the hull fails
Offset the lines and dots with ET_OPENROUND
> [FIX] Concave hull: fix cases when all points inline

- orangecontrib/text/widgets/owwikipedia.py
Wikipedia widget was broken and not shown.
Fix import of a moved module.
> [FIX] Wikipedia: make widget useable again

- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/widgets/owpreprocess.py
Fixes #669
Changes the behaviour of absolute frequency filter to return no upper cutoff point when the values of both boxes are equal.
> [FIX] Preprocess Text: set highest absolute frequency

- orangecontrib/text/widgets/owcorpusviewer.py
Corpus Viewer contains a line of code that changes the size of QSplitter. This line causes the widget to crash when executed since it uses wrong data type for size parameters. 
- Fixed the issue.
> Corpus Viewer: fix QSplitter size

- orangecontrib/text/ontology.py
- orangecontrib/text/semantic_search.py
- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/tests/test_guardian.py
- orangecontrib/text/topics/lsi.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/vectorization/simhash.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
- requirements.txt
Embedder module in core Orange changed callbacks to callbacks which report percentage instead of success.
Extra: Gensim has a new release and so one of the tests in topic modelling started to fail to remind us to set the random seed for lsi.
- Updates callbacks in document embedding
- Update callbacks in semantic search
- Setting the random seed for LSI
- Fix some other deprecations found in the module
> [FIX] Update embedder callbacks

- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/owontology.py
- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/owsemanticviewer.py
- orangecontrib/text/widgets/owwordenrichment.py
- orangecontrib/text/widgets/owwordlist.py
- orangecontrib/text/widgets/tests/test_owkeywords.py
- orangecontrib/text/widgets/tests/test_owontology.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owsemanticviewer.py
- orangecontrib/text/widgets/utils/tests/test_words.py
- orangecontrib/text/widgets/utils/words.py
Similar code for `word` table creation appears in many widgets.
Eliminate the duplicated code by creating a new module `words`
> Remove duplicated code for 'word' table creation

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/resources/wordcloud-script.js
Fixes #829. 
Modified font size scaling such that it depends on the area of the word cloud. Results before (top row) and after (bottom row) the modification:
> Word Cloud: change scaling

- orangecontrib/text/annotate_documents.py
- orangecontrib/text/tests/test_annotate_documents.py
Interface of keywords module was slightly changed with merging https://github.com/biolab/orange3-text/pull/834 which caused annotator widget to fail.
A small change in the annotator module to make annotation work again.
> [FIX] Annotate documents: update to work with the latest changes in keywords

- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/tests/test_simhash.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/vectorization/simhash.py
- orangecontrib/text/widgets/owbagofwords.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/owsimhash.py
- orangecontrib/text/widgets/tests/test_owbagofwords.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owsimhash.py
- orangecontrib/text/widgets/utils/owbasevectorizer.py
- orangecontrib/text/widgets/utils/tests/test_owbasevectorizer.py
The original issue is that the Embedder widget and embedder method is not based on the base vectorizer.
To enable basing on `BaseVectorizer`/`OWBaseVectorizer` several changes need to be made in both classes
- Implement concurrent mixin in OWBaseVectorizer (consequently it is used in Simhash and Bow)
- Reimplement commit (do not compute if the commit is unchecked until the button pressed)
- Use deferred commit
- Change embedded to base on BaseVectorizer
- Add some tests
> [ENH] Computation in separate thread for base vectorizer; use base vectorizer for embedding

- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpubmed.py
- orangecontrib/text/widgets/owtwitter.py
At least with  PyQt5 5.15.6 on linux simply running
```bash
python -c "import orangecontrib.text.widgets.ownyt"
```
pops-up a Unlock wallet/keychain,... dialog. Rejecting it then prints
```
Failed to get secret '__pyqtSignature__' of ''Orange3 - NY Times API Key''.
File "/home/ales/devel/orange3/Orange/widgets/credentials.py", line 42, in __getattr__
return keyring.get_password(self.service_name, item)
File "/home/ales/.envs/orange3/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password
return get_keyring().get_password(service_name, username)
File "/home/ales/.envs/orange3/lib/python3.10/site-packages/keyring/backends/chainer.py", line 51, in get_password
password = keyring.get_password(service, username)
File …
```
> [FIX] Credential manager dialog at import

- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/vectorization/sbert.py
While migrating between clusters, we used the `apiv2.garaza.io` address for embedders. It is deprecated and will be removed in the future. Replace it with `api.garaza.io`
> replace old apiv2.garaza.io with api.garaza.io for embedders

- orangecontrib/text/widgets/owcreatecorpus.py
- orangecontrib/text/widgets/owldavis.py
- orangecontrib/text/widgets/owtwitter.py
- orangecontrib/text/widgets/tests/test_owcreatecorpus.py
- requirements.txt
According to https://github.com/conda-forge/orange3-text-feedstock/pull/54 some dependencies are missing in requirements (orange's dependencies) and on some places we import PyQt5 instead AnyQt
Fix issues describe above
> Fix dependencies

- orangecontrib/text/semantic_search.py
- orangecontrib/text/tests/test_semantic_search.py
Semantic search embedder is slow (computation last up to 60 s for long documents in average 13s).
This PR does not speed it up much (just a bit) with the following changes:
- api.garaza.io replaces deprecated apiv2.gara.io
- requests are sent per document (not in batches anymore) - it improves the caching since it does not depend on completely the same batch - it does not slow down since the bottleneck is slow embedded (sending is not a problem)
- sort documents by their size before sending them to the server  - long documents should start embedding first since they can embed for even more than a minute on the CPU - if one such embedding starts embedding towards the end the process just wait for this document to be done
Some more improvements will follow with GPU embedder coming soon
> Semantic search: optimization

- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
Fixes #864.
Handle preprocessed corpus in Sentiment Analysis.
> OWSentimentAnalysis: Handle preprocessed corpus

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
After changes in document embedding score documents started to fail (when using embedding as similarity)
Fix score documents to latest changes and change tests such that they will fail on similar occasions the next time
> [FIX] Score Documents - adapt to the latest changes in document embedding

- orangecontrib/text/__init__.py
- orangecontrib/text/misc/nltk_data_download.py
- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/tests/test_nltk_download.py
- get_proxy from core Orange is not working properly - it document affects embeddings
- nltk needs explicit port address in proxy URL
- temporary add the same function as in https://github.com/biolab/orange3/pull/6028 to text util core Orange is released
- for NLTK add a port to the address if missing. Guess port based on the scheme. If any other port is needed user should specify it
> Fix proxy addresses for embedders and NLTK

- orangecontrib/text/tests/test_sbert.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/vectorization/sbert.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
- orangecontrib/text/widgets/utils/owbasevectorizer.py
Implements #639.
Added multilingual SBERT into Document Embedding widget.
> [ENH] Document Embedding: add SBERT

- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
- orangecontrib/text/widgets/utils/owbasevectorizer.py
Currently fasttext is default embedder
Set SBERT as default
> [ENH] Document Embedding - set SBERT as default

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/topics.py
- orangecontrib/text/vectorization/base.py
- orangecontrib/text/widgets/owtopicmodeling.py
> [FIX] Corpus: fix ngrams_corpus

- orangecontrib/text/vectorization/sbert.py
Fixes https://github.com/biolab/orange3-text/issues/832
When the other event loop which seems to be not running exist by QT we run the embedding process in the thread
> [FIX] Ontology - fix cannot be called from a running event loop error

- orangecontrib/text/tests/test_corpus.py
`__eq__` deprecation was merged after the last release, so we cannot remove it now. 
This PR moves the deletion of `__eq__` into the next release.
> Corpus - postphone removing eq deprecation

- orangecontrib/text/topics/lsi.py
- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
- requirements.txt
Temporarily fixes https://github.com/biolab/orange3-text/issues/820 until Gensim provides a solution
- Fix Gensim to version 4.1.2 - which is the last version where coherence still works
- Temporarily remove random seed for LSI since it is not compatible with 4.1.2
- Change the use of buttonClicked signal to be compatible with PyQt6
The first and second changes should be reverted when Gensim fixes CoherenceModel the last one should stay.
> Topic modelling - temporarily fix gensim to 4.1.2

- orangecontrib/text/widgets/owguardian.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/owpubmed.py
- orangecontrib/text/widgets/owtwitter.py
- In PyQt6, they completely removed `exec_` for opening dialogues as of PyQt5 already, `exec` is available.
- `addSpace` keyword is deprecated and, in my opinion, not needed (the user interface already looks good with normal spacing)
- replacing `exec_` with `exec`.
- removing `addSpace` in several widgets. It can be replaced by a separator, but in my opinion, it is not necessary.
> [FIX] Replace exec_ with exec and fix deprecations

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_bowvectorizer.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpustonetwork.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
`__eq__` was deprecated and needs to be removed
- Remove corpus's `__eq__` method to be compatible with the table which does not have it.
- Adapt tests that started to fail because of removal
- Fix some PyQt6 incompatibilities
> Remove corpus's __eq__

- orangecontrib/text/vectorization/sbert.py
Now SBERT embedded support single text (not only list of texts)
Send a text without packing it to list
> SBERT - send single text to embedder instead of list with one text

- orangecontrib/text/tests/test_ontology.py
- orangecontrib/text/tests/test_sbert.py
- orangecontrib/text/vectorization/sbert.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
SBERT was sending one text per request to the server but still received 2D results as a response.
Since from today on, the response is a 1D list when sending only one document, adapt the script to the latest canges
> SBERT - consider 1D response when sending one text per request

- orangecontrib/text/corpus.py
- orangecontrib/text/vectorization/bagofwords.py
`extend_attributes` wrongly adds the original variable to the compute_value. It actually adds a current variable. This causes infinite recursion when computing the hash value of the variable/SharedComputeVariable.
Since the wrong variable is added and it is actually never used, I am removing it.
> [FIX] VectorizationComputeValue - remove wrongly set "original" variable

- orangecontrib/text/widgets/owwordenrichment.py
Word Enrichment is not compatible with PyQt6.
Fix PyQt6 compatibility. Note that other incompatibilities are already addressed in other opened PRs.
> [FIX] Word Enrichment - fix PyQt6 incompatibility and sort imports

- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/owscoredocuments.py
Fixes https://github.com/biolab/orange3-text/issues/811
Selecting with mouse and programmatically selecting by `_select_rows` on every click causes clearing the selection and re-emitting the `selectionChanged` signal, which clears the selection.
Only switch to manual selection without reselecting items programmatically when selection is made in the table/listview.
> [FIX] Keywords/Score Documents - fix ctrl/cmd selection

- orangecontrib/text/ontology.py
- orangecontrib/text/tests/test_ontology.py
- orangecontrib/text/widgets/owontology.py
- orangecontrib/text/widgets/tests/test_owontology.py
- Fixes https://github.com/biolab/orange3-text/issues/824
- Ontology fails when embedding cannot be computed for some terms.
- OWOntology is not compatible with PyQt6
- Since now SBERT sends single documents (words in the case of ontology) to the server, and SBERT embedded already uses an embedding cache, a separate ontology cache is no longer required. **This PR removes the ontology embedding cache.** Anyway, sending single words to the embedded is not optimal and is slow in the case of terms, so in the future, I will change the SBERT embedded to have the option to send more words in the single request (and the cache will be handled there).
- **This PR also removes the similarity cache**. It is not required since I found out that it is faster to compute pairwise cosine similarity (for …
> [FIX] Ontology - remove cache and other fixes

- orangecontrib/text/widgets/owannotator.py
- orangecontrib/text/widgets/tests/test_owannotator.py
The widget crashes with
```
File "/Users/vesna/orange-widget-base/orangewidget/gui.py", line 2258, in __call__
self.func(**kwds)
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owannotator.py", line 327, in __on_clustering_type_changed
self._run()
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owannotator.py", line 379, in _run
self.graph.update_clusters()  # Remove cluster hulls and labels
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owannotator.py", line 154, in update_clusters
self._update_cluster_hull()
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owannotator.py", line 162, in _update_cluster_hull
hulls = self.master.get_cluster_hulls()
File …
```
> [FIX] Annotator: Invalidate clusters on setting change

- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
In some rare cases in cases of words appearance, scores were boolean instead of numeric values (when aggregation result was inside the bool range -- for example, when using min aggregation). It caused the widget to crash when plotting range bars. 
Cast word appearance scores to float before aggregating.
> [FIX] Score Documents - cast bool scores to float

- tox.ini
Error is raised, and tests fail every time Orange deprecate the function that the text is using. Sometimes it is not possible to replace deprecation since we must also support the oldest Oranges versions.
Raise error for Orange deprecations only in the oldest test.
> CI - Raise error for Orange deprecation warning only in oldest test

- .github/workflows/test.yml
- requirements.txt
Mac0s 10.15 workers are deprecated and we do not test py 3.9 and 3.10. 
Since it seems that it will take some time to adopt https://github.com/biolab/orange3-text/pull/917 I propose quick version fix here
> Ci - quick fix

- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/tests/test_owimportdocuments.py
Add language detection and selection functionalities
> [ENH] Import documents - language dialog and language guessing

- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/twitter.py
Adding language to the corpus
Twitter widget use language set by the user; if language is not set and all tweets have the same language, it is set as Corpus'es language. When tweets are in different languages, the language is set to None. 
I also changed the Twitter widget so that variables are initialized when Corpus is built. Before, the same variable instance was used multiple times, and those settings were shared (values, ....).
Also removing redundant enumerations.
> [ENH] Twitter - add language to corpus

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
The Corpus viewer is slow on data with multiple items (>10000). The initialization takes more than 20s on data with 100 000 documents due to a slow item model (for listing documents) and inefficient storing of selected documents (by name) which cause slow construction of output Corpus and using `findall` to identify whether a document contains a set of terms or not. Also, document filtering is made by repopulating the model instead of using QSortFilterProxyModel.
- Speed up the document table view populating by using the custom model.
- Using `regex.search` instead of `findall` for filtering documents (`findall` is still used for counting matches but in a separate thread that does not block the GUI).
- store selected documents as indexes (for after output Corpus creation)
- some other …
> Speedup corpus viewer

- orangecontrib/text/widgets/tests/test_owcreatecorpus.py
Tests in creating corpus widget started to fail since it seems that wrong button was clicked 
Fixing that the correct button is clicked
> Create corpus - fix tests

- doc/widgets/score-documents.md
- orangecontrib/text/corpus.py
- orangecontrib/text/widgets/owscoredocuments.py
- orangecontrib/text/widgets/tests/test_owscoredocuments.py
Currently Score Document matches only words from the input. When more-term words are on input, it fails with scoring (only score with first word from the term).
- Apply same preprocessing on words that are used on corpus
- Match n-grams from the corpus
With this modifications Corpus's preprocessing defines how words are preprocessed and matched. E.g. if the user selects to use bi-grams (only) on the corpus, terms (from words input) are matched as bigrams. In this case terms that are words are ignored, and those that are longer than bigrams are transformed to bigrams.
> [ENH] Score Documents - enable matching n-grams

- orangecontrib/text/widgets/owsemanticviewer.py
- orangecontrib/text/widgets/tests/test_owsemanticviewer.py
The semantic viewer only shows documents when they are scored (words are at the input)
Show documents (without scores) when there are no words in the input.
> [ENH] Semantic Viewer - show document when no words at the input

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
Corpus's method `extend_attributes` does not preserve the Corpus name
Preserve Corpus name in `extend_attributes`
> [FIX] Corpus - preserve name in extend_attributes

- orangecontrib/text/widgets/tests/test_owsemanticviewer.py
One Semantic Viewer's test still calls the API, so this test is slow.
Make sure that cache is cleared before and after the test and that API call is mocked
> Semantic Viewer - Speedup tests

- orangecontrib/text/widgets/owtopicmodeling.py
CoherenceModel is slow. But using multiprocessing for small corpora is even slower.
I am speeding up the CoherenceModel using only one process on corpora smaller than 100 documents. There needs to be better evidence of what is appropriate threshold for multiprocessing. Still, from my experiments I am sure that disabling multiprocessing for less than 100 documents is faster, even on corpora with longer documents.
> Topic modelling - speedup for small corpora

- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
Sentiment tests are slow since they download information from the server
Mock server calls to speedup tests
> Sentiment - speedup tests

- orangecontrib/text/widgets/utils/tests/test_utils.py
enum2int is now available from Orange3.
Remove it when Orange3-text can depend on Orange 3.35
> Time bomb for removing enum2int

- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
Fixes #903 
Copy corpus before change
> [FIX] Corpus widget - preserve corpus's preprocessing

- orangecontrib/text/tests/test_wikipedia.py
- orangecontrib/text/widgets/owwikipedia.py
- orangecontrib/text/widgets/utils/widgets.py
- orangecontrib/text/wikipedia_api.py
Add language to the corpus. Always add search language since all results will be in this language.
I also removed setting text colour in the ListEdit, since it causes the colour is also black in dark mode. Now, the default colour is used (white for dark mode and black for bright mode).
> [ENH] Wikipedia - add language to corpus

- orangecontrib/text/widgets/owontology.py
- orangecontrib/text/widgets/tests/test_owontology.py
When ontologies are imported, the tree shows node name instead of node label. 
Name is not necessarily in human-readable format (can be codes), but the label attribute usually shows name in a human-readable format. Show label if exists and name if label not assigned.
> [FIX] Ontology - Show labels instead of names for imported ontolgies

- orangecontrib/text/corpus_to_network.py
It would be useful to enable further examination of documents, selected in the Network Exporler, when the selected NodeType (Corpus to Network) is `Documents`. Currently this is not possible, because the Node Data's type (output of Corpus to Network) is always a `Table`.
Change the Node Data type to Corpus when the Node type == Documents.
> CorpusToNetwork: Output Corpus when type=Document

- orangecontrib/text/guardian.py
- orangecontrib/text/tests/test_guardian.py
- orangecontrib/text/util.py
- orangecontrib/text/widgets/owguardian.py
Infer language from articles and add it to the corpus
In the current implementation, Corpus variables are created when GuardianAPI is initialized, so they are shared between multiple corpora. The problem appears when different values are added to DiscreteVariable by different calls, so values accumulate. This PR changes that variables are defined in each call separately.
> [ENH] Guardian - infer language and add to corpus

- orangecontrib/text/tests/test_documentembedder.py
- orangecontrib/text/vectorization/document_embedder.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
Use language from Corpus in the Document embedding widget
> [ENH] Document embedding - Use language from the corpus

- orangecontrib/text/nyt.py
- orangecontrib/text/tests/test_nyt.py
- orangecontrib/text/util.py
- orangecontrib/text/widgets/ownyt.py
Set language to the corpus. For NY Times, it is always English.
In the current implementation, Corpus variables are created when NYT is initialized, so they are shared between multiple corpora. The problem appears when different values are added to DiscreteVariable by different calls, so values accumulate. This PR changes that variables are defined in each call separately.
> [ENH] NYTimes - add language to corpus

- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/tests/test_owkeywords.py
```
...
File "../orange3-text/orangecontrib/text/widgets/owkeywords.py", line 270, in <lambda>
callback=lambda: self._set_selection_method(
TypeError: OWKeywords._set_selection_method() takes 1 positional argument but 2 were given
```
When making a widget PyQt6 compatible in https://github.com/biolab/orange3-text/pull/929, I missed a callback causing the issue.
Also at that time, I didn't know that `buttonClicked[int]` was removed on behalf of `idClicked`. So instead of changing the callback I am reverting the `_set_selection_method` to the previous state and using `idClicked` callback instead.
> [FIX] Keywords: Fix selection and use idClicked instead of buttonClicked

- requirements.txt
Gensim made changes in wheel building and accidentally started to build the package with the newest version
https://github.com/RaRe-Technologies/gensim/pull/3467.
Skip 4.3.1, which is built with the newest Numpy. 4.3.0 is fine.
> Omit Gensim version 4.3.1

- orangecontrib/text/widgets/owimportdocuments.py
`.format` did not allow a proper translation into Slovene.
Change from `.format` to `f`-string.
> Import Documents: .format to f string

- orangecontrib/text/widgets/owontology.py
Because ontology keyword was only "ontology", it did not get a separated translation string (because a few rows down, there is another "ontology" and it would be better if they are somehow separated).
I added a new keyword.
> Ontology: added new keyword

- orangecontrib/text/import_documents.py
- orangecontrib/text/tests/test_import_documents.py
- requirements.txt
Fixes https://github.com/biolab/orange3-text/issues/974
`lxml` library is used only in importing documents to read XML files. They still didn't provide MacOS ARM wheels (Apple silicon), so installing text add-ons for users with Apple Silicon without certain compilers fails.
Since there exists an [ElemntTree](https://docs.python.org/3.9/library/xml.etree.elementtree.html#module-xml.etree.ElementTree) alternative to read XML, I propose replacing lxml. ElementTree is considered fast since it uses fast c implementation and it comes with python. I see a situation as a good way to eliminate one dependency.
> [FIX] import_documents - replace lxml xml parser with ElementTree

- orangecontrib/text/widgets/owstatistics.py
- orangecontrib/text/widgets/tests/test_owstatistics.py
When I changed `Vowel count` to `Starts with`, the pattern stayed `a,e,i,o,u` instead of going blank (` `).
It goes to default value now.
> Statistics: default value for feature pattern

- orangecontrib/text/widgets/ownyt.py
- orangecontrib/text/widgets/tests/test_ownyt.py
- In the NY Times widget - section `Text includes` is missing its attributes.
- Fixes #972  
- Change in line 82, so that attributes are now shown.
- Added if sentence to show report if there is any data. Otherwise is just blank report.
> [FIX] NY Times: missing attributes in Text includes & fixed report crashes

- orangecontrib/text/widgets/owstatistics.py
On Windows + button is hidden when the user opens the widget. Also, stretching is not optimal: empty space between the box and Apply button, and the whole box stretches instead of adding space at the bottom.
Update layout according to issue description.
Additionally, added missing `__eq__` and `__hash__` to ComputeValue.
> [FIX] Statistics - Fix layout (hidden + button on Windows)

- orangecontrib/text/keywords/mbert.py
- orangecontrib/text/tests/test_keywords.py
- orangecontrib/text/widgets/owkeywords.py
- orangecontrib/text/widgets/tests/test_owkeywords.py
Fixes https://github.com/biolab/orange3-text/issues/890
Handle connection errors and warn users about them.
> [FIX] Keywords - Handle connection error

- orangecontrib/text/ontology.py
- orangecontrib/text/tests/test_ontology.py
- orangecontrib/text/widgets/owontology.py
When ontology have multiple root elements `Include` button is disabled
This PR enables inserting in the ontology with multiple root elements. Since the method require one root element, the temporary root is added and removed after insertion.
This PR additionally speeds up the test with mocking calls to the embedding server.
> [ENH] Ontology - Enable insert in ontology with multiple roots

- orangecontrib/text/widgets/owontology.py
Removing the `bar` word from the above ontology causes an error:
```
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owontology.py", line 803, in __on_ontology_data_changed
self.__set_current_modified(self.CACHED)
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owontology.py", line 899, in __set_current_modified
ontology = self.__ontology_view.get_data()
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owontology.py", line 324, in get_data
return _model_to_tree(self.__root, selection, with_selection)
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owontology.py", line 57, in _model_to_tree
_model_to_tree(item.child(i), selection, with_selection)
File "/Users/vesna/orange3-text/orangecontrib/text/widgets/owontolog …
```
> [FIX] Ontology: Fix 'remove word' bug

- orangecontrib/text/widgets/utils/tests/test_widgets.py
- orangecontrib/text/widgets/utils/widgets.py
Fixes https://github.com/biolab/orange3-text/issues/850
Open file dialogue in previous location
> [FIX] Corpus - Open file dialogue at previous location

- orangecontrib/text/corpus.py
- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_corpus.py
- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/topics.py
- orangecontrib/text/vectorization/bagofwords.py
- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Fixes https://github.com/biolab/orange3-text/issues/920
Corpus saves a dictionary (Gensim Dictionary) which is created on first need and cached. The problem with the dictionary is that it stays the same after subsampling Corpus (creating a corpus with the subset of documents) even though the number of unique tokens changes. The most problematic is that it was used to access a number of unique tokens in Corpus at different locations in the addon. The information was incorrect after the corpus was subsampled (issue in #920).
Since the dictionary was primarily introduced for Topic modelling purposes and topic modelling does not use it anymore, I decided to remove it from Corpus. All pieces of code that use a dictionary can be written differently. 
This PR so removes the dictionary and …
> [FIX] Corpus - remove dictionary and fix wrong types count on subsampled corpus

- orangecontrib/text/tests/test_corpus.py
Dictionary deprecation was planned in version 1.15, and total removal was planned for version 1.16. Since #990  was merged after 1.15, it is not valid anymore.
Since deprecation will be introduced in 1.16, the dictionary removal is postponed to version 1.17
> Corpus dictionary - Postpone its removal 

- orangecontrib/text/widgets/owldavis.py
- orangecontrib/text/widgets/tests/test_owldavis.py
Fixes https://github.com/biolab/orange3-text/issues/1001
Fix the issue that happens after selected_topic is set to None by view. 
Reproduced:
1. Set valid data
2. Set not valid data or remove input
3. Set valid data again
> [FIX] LDAVis - Fix fail after None data

- orangecontrib/text/tests/test_annotate_documents.py
- orangecontrib/text/widgets/tests/test_owannotator.py
Annotator tests started to fail due to changes in scikit-learn (in version 1.3.0). The reason is using the same random seed returns different results since clusters in data are not well distinguishable. 
Fix the issue with artificial embeddings to produce better distinguishable clusters.
> Fix failing tests

- orangecontrib/text/tag/pos.py
- orangecontrib/text/tests/test_tags.py
- orangecontrib/text/widgets/owpreprocess.py
I am splitting #963 into smaller PRs for easier review.
StanfordPOSTagger is deprecated and unused. https://github.com/nltk/nltk/pull/1843
StanfordPOSTagger was excluded in #506 since it should be implemented in the server (as far as I understood correctly - it uses Java). If we decide to do this, it will be a completely new implementation, so I suggest removing it for now and writing an issue that we remember.
> POS - remove unsupported and unused StanfordPOSTagger

- orangecontrib/text/widgets/owtopicmodeling.py
- orangecontrib/text/widgets/tests/test_owtopicmodeling.py
LDA is a more relevant method than LSI, so it should be the default
Changing the ordering of methods and fixing settings for backwards
> [ENH] Topic modelling - Reorder methods by relevance

- orangecontrib/text/widgets/owtopicmodeling.py
Topic modelling run recomputation everytime spin focus is lost (even when value doesn't change)
Do not rerun if spin value doesn't change
> [FIX] Topic Modelling - Do not recompute when spin value doesn't change

- orangecontrib/text/annotate_documents.py
- orangecontrib/text/keywords/__init__.py
- orangecontrib/text/language.py
- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owannotator.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owannotator.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
This PR is part of #963, which I am splitting into smaller pieces for easier review. 
The main motivation behind this is to make Preprocess work with language from Corpus.
This PR prepare a stop word filter to communicate (get and return languages) as ISO codes, which is necessary to enable language from Corpus (languages are stored in Corpus in ISO format). 
After I changed Stop Word to work with ISO language codes, I also had to adapt the Preprocess Widget to store settings as ISO codes and call the StopWords filter with ISO language code.
> [ENH] Filter - Use ISO language in StopwordsFilter

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
The test warning about the dictionary needing to be removed started to fail.
Remove the deprecated dictionary, which is not used anymore.
> Corpus - Remove dictionary

- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
This PR is part of https://github.com/biolab/orange3-text/pull/963, which I am splitting into smaller pieces for easier review.
The main motivation behind this is to make Preprocess work with language from Corpus.
This PR prepare a Lemmagen normalizer to communicate (get and return languages) as ISO codes, which is necessary to enable language from Corpus (languages are stored in Corpus in ISO format).
After I changed Lemmagen to work with ISO language codes, I also had to adapt the Preprocess Widget to store settings as ISO codes and call the Lemmagen filter with ISO language code.
Udpipe and Snowball will be implemented in separate PRs.
> [ENH] Lemmagen - Use ISO language codes

- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
This PR is part of https://github.com/biolab/orange3-text/pull/963, which I am splitting into smaller pieces for easier review.
The main motivation behind this is to make Preprocess work with language from Corpus.
This PR prepare a Snowball normalizer to communicate (get and return languages) as ISO codes, which is necessary to enable language from Corpus (languages are stored in Corpus in ISO format).
After I changed Snowball to work with ISO language codes, I also had to adapt the Preprocess Widget to store settings as ISO codes and call the Lemmagen filter with ISO language code.
Udpipe will be implemented in separate PRs.
> [ENH] Snowball - Use ISO language codes

- orangecontrib/text/language.py
- orangecontrib/text/widgets/owcorpus.py
- orangecontrib/text/widgets/owcreatecorpus.py
- orangecontrib/text/widgets/owdocumentembedding.py
- orangecontrib/text/widgets/owimportdocuments.py
- orangecontrib/text/widgets/owsentimentanalysis.py
- orangecontrib/text/widgets/tests/test_owcorpus.py
- orangecontrib/text/widgets/tests/test_owcreatecorpus.py
- orangecontrib/text/widgets/tests/test_owdocumentembedding.py
- orangecontrib/text/widgets/tests/test_owimportdocuments.py
- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
In the beginning, I was keeping language names in widget settings. It turned out it is better to keep languages as ISO codes since language names can change in the future (like we did with Ancient Greek), but ISO codes will probably not.
This 
- It should fix the issue reported in https://github.com/biolab/orange3-text/pull/1030
- Change the `Ancient greek` language to `Ancient Greek` to be compatible with other languages (and compatible with ISO standards).
- Keep languages as ISO codes in settings to bypass problems with language name changes and easier management.
> [ENH] Use ISO language setting in widgets

- orangecontrib/text/widgets/owstatistics.py
- orangecontrib/text/widgets/tests/test_owstatistics.py
Regex counter counts only appearances in tokens, which ignore multi-word appearances.
As discussed with @ajdapretnar, I added a dropdown beside each statistic so that the user can decide whether to do computation on tokens/ngrams or a full document. Currently, it includes two options:
- Preprocessed tokens - Statistics are computed on either tokes or ngrams, depending on what is more suitable for the statistic.
- Documents - statistic computed on full document text
- ~Is `Preprocessed tokens` a good term, or do we have any other idea?~ Changed to `Tokens`
- ~`Average word length` is currently implemented only on documents since the name doesn't make sense on N-grams. Should we rename it to `Average term length` and apply it to documents and n-grams? So that it is word length on documents …
> [FIX] Statistics - Regex count in whole document to only token

- orangecontrib/text/language.py
- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
This PR is part of https://github.com/biolab/orange3-text/pull/963, which I am splitting into smaller pieces for easier review.
The primary motivation behind this is to make Preprocess work with language from Corpus.
This PR prepare a UDPIPE normalizer to communicate (get and return languages) as ISO codes, which is necessary to enable language from Corpus (languages are stored in Corpus in ISO format).
After I changed UDPIPE to work with ISO language codes, I also had to adapt the Preprocess Widget to store settings as ISO codes and call the Lemmagen filter with ISO language code.
This PR also slightly change the names of UDPIPE languages in the dropdown. The change is that the names of language variations (different models for the same language) are now written in parenthesis, and all …
> [ENH] UDPIPE - Use ISO language codes 

- orangecontrib/text/widgets/owannotator.py
- orangecontrib/text/widgets/tests/test_owannotator.py
When a corpus contains continuous metas, they are used for plotting instead of t-SNE variables.
Use heuristics to set t-SNE variables as default variables for plotting.
> OWAnnotator: add heuristics for choosing the right x and y

- orangecontrib/text/widgets/owpreprocess.py
`pkg_resources` is deprecated
Replacing pkg_resources with `os.path`
> [FIX] Preprocess - Replace deprecated pkg_resources

- orangecontrib/text/widgets/owwordlist.py
- orangecontrib/text/widgets/tests/test_owwordlist.py
Currently, adding a list copied entries from a previous list. This is counterintuitive. Add a separate option to copy a list.
Adding a new list now adds an empty list.
Another button is added with the option to copy an existing list.
> Word List: Add option to copy a list

- orangecontrib/text/corpus.py
- orangecontrib/text/tests/test_corpus.py
Fixes #1059, also see #1058 for failure. 
Because we can not expect gensim to release anytime soon, monkey patch scipy.linalg.triu when not available.
> Monkey-patch scipy.linalg.triu for gensim

- orangecontrib/text/widgets/owwordcloud.py
- orangecontrib/text/widgets/tests/test_owwordcloud.py
Implements #1040.
Add Document Count output to Word Count.
> Word Cloud: add document count to Word Count output

- orangecontrib/text/corpus.py
- orangecontrib/text/misc/nltk_data_download.py
- orangecontrib/text/tests/test_corpus.py
- requirements.txt
- tox.ini
Tests are failing
Gensim 4.3.3 has been released so I remove the temporary fix
NLTK changed pos taggers model names to downlod probably here: https://github.com/nltk/nltk/pull/3270, fixing model names to match
> Small fixes to resolve tests failures

- orangecontrib/text/keywords/__init__.py
- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/preprocess/normalize.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/owpreprocess.py
- orangecontrib/text/widgets/tests/test_owpreprocess.py
Set language combo boxes for the language from the corpus. 
Additionally, this PR changes the UDPIPE combo box to keep the same language when one wants to set language to language unavailable in UDPIPE. Previously, it was always reset to English.
> [ENH] Preprocess - Use language from Corpus

- orangecontrib/text/import_documents.py
- orangecontrib/text/tests/test_import_documents.py
- orangecontrib/text/widgets/tests/data/conllu/ParlaMint01-meta.tsv
- orangecontrib/text/widgets/tests/data/conllu/ParlaMint02-meta.tsv
CoNLL-U files were only matched by "Text_ID". However, sometimes the data should be matched by "ID".
This is only a workaround, until we figure out how could the user define the proper column for joining metas to corpus.
Please, can someone comment on the tests?
> Import Documents: add options for meta matching in CoNLL-U

- orangecontrib/text/tests/test_twitter.py
- orangecontrib/text/widgets/tests/test_owcollocations.py
- orangecontrib/text/widgets/tests/test_owimportdocuments.py
- requirements.txt
- tox.ini
This also solves Python 3.12 compat problems and requires Orange3 3.38.1 for httpx compat fix
> Fix import documents widget tests for new metadata handling

- orangecontrib/text/tests/test_topic_modeling.py
- orangecontrib/text/topics/topics.py
Topic Modeling failed when POS tags were included. This happened because pos_tags were somehow included twice (once in bow names, then added again in dictionary).
Do not include POS tags in dictionary else it results in empty keep parameter.
> Topic Modeling: fails on POS tags

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
Fixes #1068 
Instead of crashing, a warning message is thrown on bad regex.
> [FIX] Corpus viewer: warn on bad regex

- orangecontrib/text/language.py
- orangecontrib/text/preprocess/filter.py
- orangecontrib/text/tests/test_preprocess.py
- orangecontrib/text/widgets/tests/test_owcreatecorpus.py
NLTK added Albanian as one of the languages for stopwords. Fixes https://github.com/biolab/orange3-text/issues/1099
- Add Albanian to the dictionary of languages.
- Make sure that the next time NLTK adds a language module, it doesn't fail.
- Introduce a test that will warn about the new language.
> [FIX] Add Albanian to dictionary of languages

- orangecontrib/text/widgets/tests/test_owsentimentanalysis.py
The test fails on Windows where paths with \ and / are compared.
Fix the test by replacing \ with / before comparison.
> [FIX] test_owsentimentanalysis - Fix path comparison in failing test

- orangecontrib/text/widgets/owcorpusviewer.py
- orangecontrib/text/widgets/owpreprocess.py
Fixed #1074 
Added thousands separator to Preprocess Text and Corpus Viewer.
> Preprocess thousand separator

- orangecontrib/text/import_documents.py
- orangecontrib/text/widgets/tests/test_owcorpusviewer.py
Tests were failing in:
- `TestPdfReader.test_error`
- `TestOWImportDocuments` (warning text, skipped documents count)
- `TestOWCorpusViewer.test_search` (n_matches type mismatch)
- Updated `PdfReader` to return `None` for corrupted/empty PDFs.
- Adjusted `OWImportDocuments` warning message and skipped documents handling.
- Ensured `OWCorpusViewer.n_matches` is stored as an integer for valid regex results.
> Fix failing tests in PdfReader, OWImportDocuments, and OWCorpusViewer
